import {Prec,Compartment,StateField,EditorState,Transaction} from '@codemirror/state';
import {EditorView,basicSetup} from 'codemirror';
import {autocompletion,completeFromList,startCompletion} from '@codemirror/autocomplete';
import {indentSelection,isolateHistory,undo,redo} from '@codemirror/commands';
import {keymap,Decoration} from '@codemirror/view';
import {javascript} from '@codemirror/lang-javascript';
import {html} from '@codemirror/lang-html';
import {markdown} from '@codemirror/lang-markdown';
import {StreamLanguage,HighlightStyle,syntaxHighlighting} from '@codemirror/language';
import {tags} from '@lezer/highlight';
import {shader} from '@codemirror/legacy-modes/mode/clike';
import {highlightExtension,widgetPlugin,sliderPlugin,updateMiniLocations,highlightMiniLocations,updateWidgets,updateSliderWidgets} from '@strudel/codemirror';
import {semanticCompletion,semanticHover,glslCompletion} from './language-service.js';
import {examples} from './examples.js';
export const palettes={dark:{background:'#171b22',foreground:'#e6edf3',keyword:'#c4a5ff',string:'#a5d6a7',number:'#ffca85',comment:'#9aa7b5',selection:'#384a61'},light:{background:'#fafafa',foreground:'#24292f',keyword:'#6639ba',string:'#136c35',number:'#934400',comment:'#637080',selection:'#d5e5f5'},midnight:{background:'#0c1420',foreground:'#dceafa',keyword:'#bca5ed',string:'#8bd5ca',number:'#efc88b',comment:'#93a8bf',selection:'#304661'},paper:{background:'#f4efe4',foreground:'#352f27',keyword:'#684780',string:'#46633b',number:'#895222',comment:'#776c5e',selection:'#dfd4bb'}};
// Monochrome and transparent colors follow Underscores' code skins.
Object.assign(palettes,{
 'mono-dark':{background:'#121212',foreground:'#e7e7e7',keyword:'#e7e7e7',string:'#bdbdbd',number:'#bdbdbd',comment:'#8a8a8a',selection:'#343434',dark:true},
 'mono-light':{background:'#f4f4f4',foreground:'#292929',keyword:'#292929',string:'#505050',number:'#505050',comment:'#737373',selection:'#dedede',dark:false},
 'transparent-dark':{background:'#12121200',foreground:'#c9cdd2',keyword:'#c9cdd2',string:'#bdbdbd',number:'#bdbdbd',comment:'#92989f',selection:'#ffffff24',dark:true},
 'transparent-light':{background:'#f4f4f400',foreground:'#353a3f',keyword:'#353a3f',string:'#505050',number:'#505050',comment:'#6e7479',selection:'#00000018',dark:false},
});
export const defaultAppearance={theme:'dark',fontFamily:'ui-monospace, SFMono-Regular, Menlo, monospace',fontSize:14,lineHeight:1.55,wrap:true,autocomplete:true,hoverDocs:true,overlayBackground:'glyphs',overlayOpacity:.75};
export function appearanceValues(settings={}){const s={...defaultAppearance,...settings};const dark=s.dark??palettes[s.theme]?.dark??['dark','midnight'].includes(s.theme);const base=palettes[s.theme]||palettes.dark;const surface=s.background||base.background;return {popupBackground:surface==='transparent'||/^#[a-f\d]{6}00$/i.test(surface)?(dark?'#121212ee':'#f4f4f4ee'):surface,popupText:s.foreground||base.foreground,activeLine:dark?'#ffffff0b':'#00000008',bracket:dark?'#ffffff24':'#00000018',selectionMatch:dark?'#ffffff18':'#00000010',searchMatch:dark?'#ffffff30':'#00000024',...palettes[s.theme]||palettes.dark,...s};}
// Same non-whitespace glyph backdrop policy as UnderscoresCodeEditor.jsx.
const glyphMark=Decoration.mark({class:'cm-genereti-glyph'});
function glyphs(doc){const ranges=[];for(let n=1;n<=doc.lines;n++){const line=doc.line(n);for(const match of line.text.matchAll(/\S+/g))ranges.push(glyphMark.range(line.from+match.index,line.from+match.index+match[0].length));}return Decoration.set(ranges,true);}
const glyphField=StateField.define({create:state=>glyphs(state.doc),update:(value,tr)=>tr.docChanged?glyphs(tr.state.doc):value,provide:field=>EditorView.decorations.from(field)});
function styling(settings){const p=appearanceValues(settings),dark=p.dark??['dark','midnight'].includes(p.theme);const overlay=!!settings.overlay,backdrop=`color-mix(in srgb, ${p.background} ${Math.round((p.overlayOpacity??.75)*100)}%, transparent)`;return [Prec.highest(EditorView.theme({'&':{height:settings.fillHeight||overlay?'100%':'260px',fontSize:`${p.fontSize}px`,color:p.foreground,backgroundColor:overlay?(p.overlayBackground==='solid'?backdrop:'transparent'):p.background,'--foreground':p.foreground},'.cm-scroller':{overflow:'auto',fontFamily:p.fontFamily,lineHeight:String(p.lineHeight)},'.cm-gutters':{backgroundColor:overlay?'transparent':p.background,color:p.comment,border:'none'},'.cm-content':{caretColor:p.foreground},'.cm-cursor':{borderLeftColor:p.foreground},'.cm-activeLine,.cm-activeLineGutter':{backgroundColor:p.activeLine+' !important'},'&.cm-focused .cm-selectionBackground,.cm-selectionBackground':{backgroundColor:p.selection+' !important'},'.cm-content ::selection,.cm-content::selection':{backgroundColor:p.selection+' !important',color:'inherit'},'.cm-matchingBracket':{backgroundColor:p.bracket+' !important',color:'inherit'},'.cm-selectionMatch':{backgroundColor:p.selectionMatch+' !important'},'.cm-searchMatch':{backgroundColor:p.searchMatch+' !important',outline:'none'},'.cm-searchMatch.cm-searchMatch-selected':{backgroundColor:p.selection+' !important'},'.cm-tooltip':{backgroundColor:p.popupBackground+' !important',color:p.popupText+' !important',borderColor:p.comment},'.cm-tooltip-autocomplete > ul > li[aria-selected]':{backgroundColor:p.selection+' !important',color:p.popupText+' !important'},'.cm-inline-widget canvas':{maxWidth:'100%'},'.cm-genereti-glyph':{background:overlay&&p.overlayBackground==='glyphs'?backdrop:'transparent',boxDecorationBreak:'clone','-webkit-box-decoration-break':'clone'}},{dark})),Prec.highest(syntaxHighlighting(HighlightStyle.define([{tag:tags.keyword,color:p.keyword},{tag:[tags.string,tags.regexp],color:p.string},{tag:[tags.number,tags.bool],color:p.number},{tag:tags.comment,color:p.comment},{tag:[tags.variableName,tags.propertyName,tags.operator],color:p.foreground}]))),p.wrap?EditorView.lineWrapping:[]];}
const completionNames={p5:'createCanvas resizeCanvas background clear fill noFill stroke noStroke strokeWeight line rect ellipse circle triangle quad bezier vertex beginShape endShape push pop translate rotate scale color colorMode random noise map constrain lerp sin cos tan abs min max width height windowWidth windowHeight frameCount deltaTime mouseX mouseY mouseIsPressed key keyCode keyIsPressed keyIsDown createVector loadImage image loadFont text textSize textAlign textFont drawingContext pixelDensity saveCanvas noLoop loop',three:'Scene PerspectiveCamera OrthographicCamera WebGLRenderer Mesh MeshBasicMaterial MeshStandardMaterial MeshPhongMaterial BoxGeometry SphereGeometry PlaneGeometry TorusGeometry Color Vector2 Vector3 Euler Quaternion Group AmbientLight DirectionalLight PointLight BufferGeometry Clock TextureLoader',glsl:'u_resolution u_time u_mouse gl_FragCoord gl_FragColor vec2 vec3 vec4 mat2 mat3 mat4 float int bool uniform varying normalize length dot cross mix smoothstep step clamp fract mod sin cos abs floor ceil texture2D'};
completionNames.strudel='note sound s stack slow fast rev gain pan room lpf hpf cps setcpm samples hush scope pianoroll _pianoroll _scope markcss';
function completions(mode){const names=completionNames[mode];if(!names)return [];return [{autocomplete:completeFromList(names.split(' ').map(label=>({label,type:mode==='glsl'?'variable':'function',info:mode==='three'?`THREE.${label}`:`${mode} · ${label}`})))}];}
export function createEditor(parent,source,mode,onChange,onRun,settings={}){
 const appearance=new Compartment();const lang=mode==='glsl'?StreamLanguage.define(shader):mode==='html'?html():mode==='markdown'?markdown():javascript();
 // Completion source identity must stay stable across state lookups, or
 // CodeMirror treats every update as a new source and discards its result.
 const semantic=['p5','three'].includes(mode);const completionControl=new Compartment(),hoverControl=new Compartment();const completionConfig=s=>autocompletion({activateOnTyping:s.autocomplete!==false,...(s.autocomplete===false?{override:[]}:mode==='glsl'?{override:[glslCompletion]}:{}) });const hoverConfig=s=>semantic&&s.hoverDocs!==false?semanticHover(mode):[];const completionData=semantic?[{autocomplete:semanticCompletion(mode)}]:mode==='glsl'?[{autocomplete:glslCompletion}]:completions(mode);
 const view=new EditorView({doc:source,parent,extensions:[basicSetup,lang,glyphField,hoverControl.of(hoverConfig(settings)),completionControl.of(completionConfig(settings)),EditorState.languageData.of(()=>completionData),mode==='strudel'?[highlightExtension,widgetPlugin,sliderPlugin]:[],appearance.of(styling(settings)),Prec.highest(keymap.of([{key:'Mod-Enter',run(){onRun();return true;}},{key:'Ctrl-Enter',run(){onRun();return true;}}])),EditorView.updateListener.of(update=>{if(update.docChanged)onChange(update.state.doc.toString());})]});
 // Comfy's older ChangeTracker schedules graph undo from a window capture
 // listener, ignoring preventDefault and contentEditable. Its text-input
 // exclusion also recognizes this textarea type marker.
 view.contentDOM.type='textarea';
 view.undo=()=>undo(view);view.redo=()=>redo(view);view.complete=()=>settings.autocomplete!==false&&startCompletion(view);
 view.replaceDocument=source=>view.dispatch({changes:{from:0,to:view.state.doc.length,insert:source},selection:{anchor:0},annotations:[Transaction.userEvent.of('input.format'),isolateHistory.of('full')]});
 view.reindent=()=>{view.dispatch({selection:{anchor:0,head:view.state.doc.length}});return indentSelection(view);};
 view.setAppearance=next=>{settings=next;view.dispatch({effects:[appearance.reconfigure(styling(next)),completionControl.reconfigure(completionConfig(next)),hoverControl.reconfigure(hoverConfig(next))]});};
 view.setStrudelVisuals=(meta,haps,time)=>{if(meta){updateMiniLocations(view,meta.miniLocations||[]);updateWidgets(view,(meta.widgets||[]).filter(w=>w.type!=='slider'));updateSliderWidgets(view,(meta.widgets||[]).filter(w=>w.type==='slider'));}if(haps)highlightMiniLocations(view,time,haps);};
 view.dom.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.shiftKey&&event.key.toLowerCase()==='f'){event.preventDefault();view.formatDocument?.();}event.stopPropagation();});view.dom.addEventListener('pointerdown',event=>event.stopPropagation());return view;
}
export {examples};
