import {test} from 'node:test';import assert from 'node:assert/strict';
import {pattern,stepTime,events,heldNotes,noteFrame} from '../integrations/genereti_comfy_chop/web/audio-sequence.js';
import {AudioPatch} from '../integrations/genereti_comfy_chop/web/modular-audio.js';
class Param{value=0;setTargetAtTime(v){this.value=v;}setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}cancelAndHoldAtTime(){}}
class Node{gain=new Param();pan=new Param();frequency=new Param();Q=new Param();delayTime=new Param();connections=new Set();connect(n){this.connections.add(n);}disconnect(n){if(n)this.connections.delete(n);else this.connections.clear();}start(){}stop(){}getFloatTimeDomainData(a){a.fill(.2);}}
function context(){const c={currentTime:0,sampleRate:48000,destination:new Node(),made:0,createBuffer(){return {getChannelData(){return new Float32Array(48000);}}}};for(const method of ['Gain','StereoPanner','BiquadFilter','Delay','DynamicsCompressor','Analyser','Oscillator','BufferSource'])c['create'+method]=()=>{c.made++;return new Node();};return c;}
test('audio-clock sequencing handles rests, simultaneous drums, swing and validation',()=>{const p=pattern('60 - 67');assert.deepEqual(events(p,1,1,.1,.6),[]);assert.equal(events(p,2,1,.1,.6)[0].note,67);assert.equal(stepTime(1,0,120,4,.2),.15);const drums=pattern('kick:10;snare:10;hat:01',true);assert.equal(events(drums,0,0,.1,1).length,2);assert.throws(()=>pattern('kick:2',true));assert.throws(()=>pattern('128'));});
test('MIDI input preserves simultaneous notes and fractional plain pitch',()=>{assert.equal(heldNotes({channels:{'ch1.note60':[1],'ch1.note64':[.5]}}).length,2);assert.equal(heldNotes({channels:{note:[60.5],gate:[1]}})[0].note,60.5);});
test('routes are reused; mixer mute/solo affect native gain; disconnect removes output',()=>{const c=context(),p=new AudioPatch(c),defs=new Map([[1,{kind:'Synth',settings:{level:.4},inputs:{}}],[2,{kind:'Mixer',settings:{master:.7,level_1:.8,level_2:.6,solo_2:true},inputs:{input_1:1}}],[3,{kind:'Output',settings:{level:.6},inputs:{input:2}}]]);p.sync(defs,new Set([3]));const allocated=c.made;p.sync(defs,new Set([3]));assert.equal(c.made,allocated);assert.equal(p.modules.get(2).inputs.input_1.gain.value,0);assert.equal(p.modules.get(2).inputs.input_2.gain.value,.6);assert(p.modules.get(3).output.connections.has(c.destination));p.sync(defs,new Set());assert.equal(p.modules.size,0);assert.equal(p.edges.size,0);});
test('reject external feedback cycles, while delay feedback is bounded',()=>{const p=new AudioPatch(context());assert.throws(()=>p.sync(new Map([[1,{kind:'Gain',settings:{},inputs:{input:2}}],[2,{kind:'Gain',settings:{},inputs:{input:1}}]]),new Set([1])),/cycles/);p.sync(new Map([[1,{kind:'Delay',settings:{feedback:2,seconds:.2,mix:.4},inputs:{}}]]),new Set([1]));assert.equal(p.modules.get(1).feedback.gain.value,.85);});
test('polyphony caps voices and panic disposes their native resources',()=>{const p=new AudioPatch(context());p.sync(new Map([[1,{kind:'Synth',settings:{level:.4,voice:'sine',polyphony:2,attack:.01,decay:.1,sustain:.6,release:.2},inputs:{}}]]),new Set([1]));for(const n of [60,64,67])p.trigger(1,n,0,.2,.6);assert.equal(p.modules.get(1).voices.size,2);p.stop();assert.equal(p.modules.size,0);});

test('sequence CHOP frames keep rests silent and represent simultaneous drum notes',()=>{assert.equal(noteFrame(pattern('60 -'),1,true,.7,0,4).channels.gate[0],0);const f=noteFrame(pattern('kick:1;snare:1;hat:0',true),0,true,.7,0,4);assert.equal(heldNotes(f).length,2);assert.equal(heldNotes(noteFrame(pattern('kick:1',true),0,false,.7,0,4)).length,0);});
