import test from 'node:test';import assert from 'node:assert/strict';
import {playActions,createRecorder} from '../integrations/genereti_comfy_agent/web/js/guide-cua.js';
function setup(){const listeners=new Map();globalThis.window={addEventListener(k,v){listeners.set(k,v);},removeEventListener(k){listeners.delete(k);}};globalThis.document={querySelector(){return null;},createElement(){return {style:{},remove(){}};},body:{append(){}}};let value='old',changes=0,before=0,after=0;const node={id:2,comfyClass:'GeneretiDatText',properties:{generetiLessonRef:'note'},widgets:[{name:'text',get value(){return value;},options:{setValue(v){value=v;}},callback(){changes++;}}],inputs:[],setDirtyCanvas(){}};const graph={_nodes:[node],getNodeById(){return node;},beforeChange(){before++;},afterChange(){after++;},setDirtyCanvas(){}};const app={graph,canvas:{}};return {app,node,listeners,get value(){return value;},set value(v){value=v;},counts:()=>({changes,before,after})};}
test('Do it uses the editor setter and commits one callback with undo hooks',async()=>{const state=setup();await playActions(state.app,[{kind:'type-text',target:{nodeType:'GeneretiDatText',nodeId:2,widget:'text'},value:'A lesson note'}],{instant:true});assert.equal(state.value,'A lesson note');assert.deepEqual(state.counts(),{changes:1,before:1,after:1});});
test('Do it stops a cancelled run before changing values',async()=>{const state=setup(),controller=new AbortController();controller.abort();await assert.rejects(playActions(state.app,[{kind:'set-widget',target:{nodeType:'GeneretiDatText',nodeId:2,widget:'text'},value:'new'}],{instant:true,signal:controller.signal}),/stopped/);assert.equal(state.value,'old');});
test('recording captures committed edits into separate steps and removes its listeners',()=>{const state=setup(),owner={id:1};const recorder=createRecorder(state.app,owner);recorder.start();state.value='First';recorder.next();state.value='Second';const steps=recorder.stop();assert.equal(steps.length,2);assert.equal(steps[0].actions[0].value,'First');assert.equal(steps[1].actions[0].value,'Second');assert.equal(recorder.running,false);assert.equal(state.listeners.size,0);});
test('wiring playback resolves named sockets through node connection APIs',async()=>{const state=setup(),src={id:3,comfyClass:'Source',outputs:[{name:'image'}],connect(out,to,input){assert.equal(out,0);assert.equal(input,0);to.inputs[input].link=7;return {id:7};}};state.node.inputs=[{name:'image',link:null}];state.node.disconnectInput=i=>state.node.inputs[i].link=null;state.app.graph._nodes.push(src);const target={nodeType:'GeneretiDatText',nodeId:2};await playActions(state.app,[{kind:'connect',target,source:{nodeType:'Source',nodeId:3},output:'image',input:'image'}],{instant:true});assert.equal(state.node.inputs[0].link,7);await playActions(state.app,[{kind:'disconnect',target,input:'image'}],{instant:true});assert.equal(state.node.inputs[0].link,null);});
test('out-of-range parameter values are rejected before changing the graph',async()=>{const state=setup();state.node.widgets[0].options.min=0;state.node.widgets[0].options.max=1;await assert.rejects(playActions(state.app,[{kind:'set-widget',target:{nodeType:'GeneretiDatText',nodeId:2,widget:'text'},value:5}],{instant:true}),/outside/);assert.deepEqual(state.counts(),{changes:0,before:0,after:0});});

test('recording/replaying builds, wires, arranges and deletes a patch with fresh node IDs',async()=>{
 const state=setup(),graph=state.app.graph;graph._nodes=[];graph.links={};let nextID=100,nextLink=1;
 graph.add=n=>{n.id=nextID++;n.graph=graph;graph._nodes.push(n);return n;};graph.remove=n=>{graph._nodes=graph._nodes.filter(other=>other!==n);};graph.getNodeById=id=>graph._nodes.find(n=>n.id===Number(id));
 const make=type=>({type,comfyClass:type,title:type,properties:{},pos:[0,0],size:[300,200],widgets:[{name:'value',value:0}],inputs:[{name:'input',link:null}],outputs:[{name:'output'}],setSize(size){this.size=size;},connect(out,to,input){const id=nextLink++;graph.links[id]={origin_id:this.id,origin_slot:out};to.inputs[input].link=id;return {id};},setDirtyCanvas(){}});
 globalThis.LiteGraph={registered_node_types:{Patch:class{}},createNode:make};
 const add=graph.add,remove=graph.remove,recorder=createRecorder(state.app,{id:1});recorder.start();
 const a=graph.add(make('Patch')),b=graph.add(make('Patch'));a.widgets[0].value=.25;a.pos=[123,456];a.mode=4;a.flags={collapsed:true};a.connect(0,b,0);recorder.next();graph.remove(b);const steps=recorder.stop();
 assert.equal(graph.add,add);assert.equal(graph.remove,remove);assert.equal(steps[0].actions.filter(a=>a.kind==='create-node').length,2);assert(steps[0].actions.some(a=>a.kind==='layout'));assert(steps[0].actions.some(a=>a.kind==='connect'));assert(steps[1].actions.some(a=>a.kind==='delete-node'));
 graph._nodes=[];graph.links={};await playActions(state.app,steps[0].actions,{instant:true});assert.equal(graph._nodes.length,2);assert.deepEqual(graph._nodes[0].pos,[123,456]);assert.equal(graph._nodes[0].widgets[0].value,.25);assert.equal(graph._nodes[0].mode,4);assert.equal(graph._nodes[0].flags.collapsed,true);assert(graph._nodes[1].inputs[0].link);
 await playActions(state.app,steps[0].actions,{instant:true});assert.equal(graph._nodes.length,2,'replay updates only matching recording references');await playActions(state.app,steps[1].actions,{instant:true});assert.equal(graph._nodes.length,1);
});
test('snapshot recording includes existing patch and leaves same-type unrelated nodes alone',async()=>{
 const state=setup();globalThis.LiteGraph={registered_node_types:{GeneretiDatText:class{}},createNode:type=>({type,properties:{},widgets:[{name:'text',value:''}],setSize(){}})};state.app.graph.add=n=>state.app.graph._nodes.push(n);
 const recorder=createRecorder(state.app,{id:1});recorder.start({includeExisting:true});const steps=recorder.stop();assert.equal(steps[0].title,'Starting patch');assert.equal(steps[0].actions[0].widgets.text,'old');
 const unrelated={...state.node,id:999,properties:{generetiLessonRef:'unrelated'}};state.app.graph._nodes=[unrelated];await playActions(state.app,steps[0].actions,{instant:true});assert.equal(state.app.graph._nodes.length,2);assert.equal(unrelated.properties.generetiLessonRef,'unrelated');
});
test('removing an idle lesson safely cancels an unstarted recorder',()=>{const state=setup();assert.doesNotThrow(()=>createRecorder(state.app,{id:1}).cancel());});
