import {app} from '../../scripts/app.js';
import {attachExecutionMode,subscribeLive,publishLive} from '/extensions/genereti_comfy_p5/js/live-runtime.js';
import {textureGPU} from '/extensions/genereti_comfy_texture/texture-gpu.js';
import {previewState} from '/extensions/genereti_comfy_p5/js/preview-state.js';
import {previewControls} from '/extensions/genereti_comfy_stream/js/preview-controls.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
import {csv} from './tables.js';
const types=new Set(['GeneretiConvertTopToChop','GeneretiConvertTopToDat','GeneretiConvertChopToTop','GeneretiConvertDatToTop']);
const states=new Set();let clock;
function values(node){const v=Object.fromEntries((node.widgets??[]).filter(w=>['number','string','boolean'].includes(typeof w.value)).map(w=>[w.name,w.value]));for(let i=0;i<(node.inputs?.length??0);i++){const slot=node.inputs[i],l=node.getInputLink?.(i),source=node.graph?.getNodeById(l?.origin_id),value=source?._generetiLiveValue?.(l?.origin_slot);if(value!==undefined&&!['IMAGE','GENERETI_CHOP','GENERETI_DAT'].includes(slot.type))v[slot.widget?.name??slot.name]=value;}return v;}
const input=node=>{const slot=node.inputs.findIndex(i=>i.name==='input'),link=slot>=0?node.getInputLink?.(slot):null;return node.graph?.getNodeById(link?.origin_id);};
app.registerExtension({name:'Genereti.Conversions',nodeCreated(node){
 if(!types.has(node.comfyClass))return;ensureControlStyle();const kind=node.comfyClass.slice('GeneretiConvert'.length),isImage=kind.endsWith('ToTop'),prefix='convert:'+crypto.randomUUID()+':';
 const surface=document.createElement('div');surface.style.cssText='width:100%;display:flex;flex-direction:column;gap:4px';
 const preview=document.createElement('div');preview.style.cssText='width:100%;position:relative;overflow:auto;max-height:200px';const frame=document.createElement('canvas');const canvas=document.createElement('canvas');canvas.width=canvas.height=1;canvas.style.cssText='width:100%;height:100%;object-fit:contain;image-rendering:pixelated';const status=document.createElement('span');status.style.cssText='font:11px monospace';if(isImage){preview.style.maxHeight='none';preview.append(canvas);}
 const local=previewState(node,preview,{resize:()=>{if(isImage)state.lastInput=null;node.setDirtyCanvas?.(true,true);}});let output;if(isImage){output=previewControls(canvas,status,node,()=>{}, {initialFrame:()=>({bitmap:frame}),getRenderSize:()=>frame});surface.append(output.toolbar);node._generetiMountTransport=()=>node._generetiExecutionModeElement?.append(output.actions);}
 surface.append(local.actions,preview,status);
 const state={node,dead:false,busy:false,last:0,table:null,signal:null,lastInput:null,signature:'',consume(p,now,v){if(state.dead)return;const channels=Object.fromEntries([...'rgba'].map((name,c)=>[name,Float32Array.from({length:p.width*p.height},(_,i)=>p.data[i*4+c]/255)]));if(kind==='TopToChop')state.signal={channels,sampleRate:Number(v.sample_rate),start:now/1000};else state.table={rows:[['x','y','r','g','b','a'],...Array.from({length:p.width*p.height},(_,i)=>[i%p.width,Math.floor(i/p.width),...Array.from({length:4},(_,c)=>p.data[i*4+c]/255)].map(String))]};window.dispatchEvent(new CustomEvent('genereti-control-frame',{detail:{nodeId:node.id}}));if(local.visible){preview.replaceChildren();const text=document.createElement('pre');text.style.cssText='font:11px monospace;white-space:pre-wrap;margin:0';text.textContent=kind==='TopToDat'?csv({rows:state.table.rows.slice(0,33)}):Object.entries(channels).map(([name,values])=>name+': '+[...values.slice(0,16)].map(v=>v.toFixed(3)).join(' ')).join('\n');preview.append(text);}status.textContent=`${p.width} × ${p.height} samples · ≤${v.sample_rate} Hz · explicit readback`;}};
 let stopInput,engine;function bind(){if(stopInput||isImage||state.dead||node._generetiExecutionMode==='Comfy Queue')return;const proxy={get id(){return node.id;},get graph(){return node.graph;},comfyClass:'GeneretiLiveImagePreview',get inputs(){return node.inputs.filter(i=>i.name==='image');},getInputLink(){return node.getInputLink(node.inputs.findIndex(i=>i.name==='image'));}};stopInput=subscribeLive(proxy,detail=>{const now=performance.now(),v=values(node);if(state.dead||state.busy||node._generetiLivePaused||node._generetiExecutionMode==='Comfy Queue'||now-state.last<1000/v.sample_rate)return;state.last=now;
  if(detail.texture){state.busy=true;state.pending=textureGPU().then(gpu=>{engine=gpu;return gpu.readPixels(detail.texture,v.sample_width,v.sample_height,prefix+'samples');}).then(p=>state.consume(p,now,v)).catch(e=>status.textContent=e.message).finally(()=>state.busy=false);}
  else{try{const c=document.createElement('canvas');c.width=Math.min(v.sample_width,detail.bitmap.width);c.height=Math.min(v.sample_height,detail.bitmap.height);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(detail.bitmap,0,0,c.width,c.height);state.consume({data:ctx.getImageData(0,0,c.width,c.height).data,width:c.width,height:c.height},now,v);}catch(e){status.textContent=e.message;}}
 },text=>status.textContent=text,{gpu:true});}
 state.update=()=>{if(!isImage||state.dead||node._generetiLivePaused||node._generetiExecutionMode==='Comfy Queue')return;const source=input(node),data=kind==='ChopToTop'?(source?._generetiChop?.latest??source?._generetiDatSignal?.()):(source?._generetiDat?.latest??source?._generetiDatTable?.()),v=values(node),signature=JSON.stringify(v);if(!data){status.textContent='Connect '+(kind==='ChopToTop'?'CHOP':'DAT')+' input';return;}if(state.lastInput===data&&state.signature===signature)return;state.lastInput=data;state.signature=signature;
  let width,height,rgba,rows;
  if(kind==='ChopToTop'){rows=Object.values(data.channels);width=v.layout==='rgba'?Math.max(1,Math.min(512,v.width)):Math.min(512,rows[0]?.length??1);height=v.layout==='rgba'?Math.max(1,Math.min(512,Math.ceil((rows[0]?.length??1)/width))):Math.max(1,Math.min(512,rows.length));}
  else{rows=v.header?data.rows.slice(1):data.rows;width=Math.max(1,Math.min(512,rows.reduce((w,r)=>Math.max(w,r.length),0)));height=Math.max(1,Math.min(512,rows.length));}
  const pixels=new Uint8ClampedArray(width*height*4),finite=x=>Number.isFinite(Number(x))?Math.max(0,Math.min(1,Number(x)))*255:0;
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;if(kind==='ChopToTop'&&v.layout==='rgba'){for(let c=0;c<4;c++)pixels[i+c]=rows[c]?finite(rows[c][y*width+x]):c===3?255:0;}else{pixels[i]=pixels[i+1]=pixels[i+2]=finite(rows[y]?.[x]);pixels[i+3]=255;}}
  frame.width=width;frame.height=height;frame.getContext('2d').putImageData(new ImageData(pixels,width,height),0,0);if(local.visible){canvas.width=width;canvas.height=height;canvas.getContext('2d').drawImage(frame,0,0);preview.style.height=Math.min(240,Math.max(32,(node.size[0]-24)*height/width))+'px';}publishLive(node,frame);output?.publish({bitmap:frame});status.textContent=`${width} × ${height} · data → IMAGE upload boundary`;
 };
 node._generetiDatTable=()=>state.table;node._generetiDatSignal=()=>state.signal;node._generetiLiveValue=slot=>slot===1?(kind==='TopToChop'?state.signal?.channels.r.at(-1):kind==='TopToDat'&&state.table?csv(state.table):undefined):undefined;
 if(isImage)node._generetiLiveSource={retain(){},release(){}};
 node._generetiSetExecutionMode=mode=>{if(mode==='Live')bind();else{stopInput?.();stopInput=null;}};
 node.addDOMWidget('conversion_preview','GENERETI_CONVERSION_PREVIEW',surface,{serialize:false,hideOnZoom:false}).computeSize=width=>[width,(local.minimized?0:isImage?Math.min(240,Math.max(32,(width-24)*canvas.height/canvas.width)):150)+80];
 states.add(state);attachExecutionMode(node);node._generetiMountTransport?.();bind();if(!clock)clock=setInterval(()=>{for(const s of states)try{s.update();}catch(error){s.node.widgets.at(-1).element.lastChild.textContent=error.message;}},100);
 const removed=node.onRemoved;node.onRemoved=function(){state.dead=true;states.delete(state);if(!states.size){clearInterval(clock);clock=null;}stopInput?.();output?.close();if(state.pending)state.pending.finally(()=>engine?.release(prefix));else engine?.release(prefix);return removed?.apply(this,arguments);};
}});
