import {app} from '../../scripts/app.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
import {parseExpression,evaluateExpression} from '/extensions/genereti_comfy_texture/expression.js';
import {documentExportControls,tableMarkdown} from '/extensions/genereti_comfy_p5/js/document-export.js';
import {parseCSV,csv,fromJSON} from './tables.js';
const states=new Set();
function read(node){const v=Object.fromEntries((node.widgets??[]).filter(w=>['number','string','boolean'].includes(typeof w.value)).map(w=>[w.name,w.value]));for(let i=0;i<(node.inputs?.length??0);i++){const link=node.getInputLink?.(i),src=node.graph?.getNodeById(link?.origin_id);if(node.inputs[i].type==='STRING'&&src?._generetiLiveValue)v[node.inputs[i].widget?.name??node.inputs[i].name]=src._generetiLiveValue(link.origin_slot);}return v;}
function tick(){const done=new Set(),visiting=new Set();function run(s){if(!s||done.has(s))return;if(visiting.has(s))throw Error('DAT cycles are not supported');visiting.add(s);s.update(run);visiting.delete(s);done.add(s);}for(const s of states)try{run(s);}catch(e){s.status.textContent=e.message;visiting.clear();}}
setInterval(tick,100);
app.registerExtension({name:'Genereti.DAT',nodeCreated(node){
 if(!node.comfyClass?.startsWith('GeneretiDat')||['GeneretiDatLesson','GeneretiDatInspect'].includes(node.comfyClass))return;ensureControlStyle();const kind=node.comfyClass.slice(11),surface=document.createElement('div'),preview=document.createElement('div'),status=document.createElement('span');surface.style.cssText='width:100%;display:flex;flex-direction:column;gap:4px;color:var(--fg-color,#eee)';preview.style.cssText='max-height:180px;overflow:auto;font:12px monospace';status.style.cssText='font:11px monospace';const tools=document.createElement('div');tools.className='genereti-node-controls';const collapse=document.createElement('button');collapse.textContent='⌄';collapse.title='Minimize table preview';collapse.setAttribute('aria-label',collapse.title);collapse.setAttribute('aria-expanded','true');tools.append(collapse);surface.append(tools,preview,status);let minimized=false;collapse.onclick=()=>{minimized=!minimized;preview.hidden=minimized;collapse.textContent=minimized?'›':'⌄';collapse.setAttribute('aria-expanded',String(!minimized));node.setSize?.(node.computeSize());node.setDirtyCanvas?.(true,true);};
 const state={node,status,latest:null,update(run){const v=read(node),input=name=>{const slot=node.inputs.findIndex(i=>i.name===name),l=slot>=0?node.getInputLink?.(slot):null,upstream=node.graph?.getNodeById(l?.origin_id),s=upstream?._generetiDat;run(s);return s?.latest??upstream?._generetiChop?.latest??upstream?._generetiDatTable?.()??upstream?._generetiDatSignal?.();},a=input('input'),b=input('other');if(kind==='Expression')v.performanceValues=window.generetiPerformance?.expressionValues();const signature=JSON.stringify(v);if(state.signature===signature&&state.a===a&&state.b===b)return;let data;
  if(kind==='Text')data={rows:String(v.text).split(/\r?\n/).map(s=>[s])};else if(kind==='Table')data=parseCSV(v.text,v.delimiter==='tab'?'\t':v.delimiter);else if(kind==='JSON')data=fromJSON(v.text);
  else if(!a){status.textContent='Connect DAT input';return;}
  else if(kind==='FromChop'){const entries=Object.entries(a.channels),names=entries.map(([name])=>name),n=entries[0]?.[1].length??0;data={rows:names.length?[names,...Array.from({length:n},(_,i)=>entries.map(([,values])=>String(values[i])))]:[]};}
  else{const rows=a.rows,w=rows.reduce((w,r)=>Math.max(w,r.length),0);if(kind==='Select'){const columns=v.columns.trim()?v.columns.trim().split(/\s+/).map(Number):Array.from({length:w},(_,i)=>i);data={rows:rows.slice(v.start,v.start+v.count).map(r=>columns.map(c=>r[c]??''))};}
   else if(kind==='Merge')data={rows:[...rows,...(b?.rows??[])]};else if(kind==='Transpose')data={rows:Array.from({length:w},(_,c)=>rows.map(r=>r[c]??''))};else if(kind==='Replace')data={rows:rows.map(r=>r.map(s=>s.replaceAll(v.find,v.replace)))};
   else if(kind==='Expression'){const tree=parseExpression(v.expression);data={rows:rows.map((r,y)=>r.map((s,x)=>String((value=>Number.isFinite(value)?value:0)(evaluateExpression(tree,{...v.performanceValues,t:0,z:0,i:y*w+x,x,y,c:x,v:Number(s)||0,a:Number(s)||0,b:0,w,h:rows.length})))))};}
   else data=a;
  }
  state.latest=data;state.signature=signature;state.a=a;state.b=b;state.text=kind==='Text'?v.text:csv(data);if(kind==='Cell'){state.cellText=data.rows[v.row]?.[v.column]??'';state.cellValue=Number.isFinite(Number(state.cellText))?Number(state.cellText):0;}
  if(kind==='ToChop'){const rows=data.rows,body=v.header?rows.slice(1):rows,w=rows.reduce((w,r)=>Math.max(w,r.length),0),channels={};for(let c=0;c<w;c++){let name=v.header?rows[0]?.[c]??'chan'+c:'chan'+c;while(name in channels)name+='_';channels[name]=Float32Array.from(body.length?body:[[]],r=>Number.isFinite(Number(r[c]))?Number(r[c]):0);}state.signal={channels,sampleRate:v.sample_rate,start:0};}
  window.dispatchEvent(new CustomEvent('genereti-control-frame',{detail:{nodeId:node.id}}));
  preview.replaceChildren();const table=document.createElement('table');table.style.cssText='border-collapse:collapse;width:100%';for(const row of data.rows.slice(0,32)){const tr=document.createElement('tr');for(const cell of row.slice(0,16)){const td=document.createElement('td');td.textContent=cell;td.style.cssText='padding:3px 6px;border-bottom:1px solid var(--border-color,#444);white-space:pre-wrap';tr.append(td);}table.append(tr);}preview.append(table);status.textContent=`${data.rows.length} rows · ${data.rows.reduce((w,r)=>Math.max(w,r.length),0)} columns${data.rows.length>32?' · preview limited to 32 rows':''}`;
 }};
 tools.append(documentExportControls(()=>({title:node.title,mode:'markdown',source:kind==='Text'?state.text??read(node).text:tableMarkdown(state.latest,node.title)}),error=>status.textContent=error.message));
 node._generetiDat=state;node._generetiDatSignal=()=>state.signal;node._generetiLiveValue=slot=>kind==='Cell'?(slot===0?state.cellText:slot===1?state.cellValue:undefined):slot===1?(kind==='ToChop'?Object.values(state.signal?.channels??{})[0]?.at(-1)??0:state.text):undefined;
 node.addDOMWidget('table_preview','GENERETI_DAT_PREVIEW',surface,{serialize:false,hideOnZoom:false}).computeSize=width=>[width,minimized?40:Math.min(180,Math.max(28,(state.latest?.rows.length??1)*25))+40];states.add(state);
 const removed=node.onRemoved;node.onRemoved=function(){states.delete(state);return removed?.apply(this,arguments);};
}});
