import {createRecorder} from '/extensions/genereti_comfy_agent/js/guide-cua.js';
import {app} from '../../scripts/app.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
import {documentExportControls} from '/extensions/genereti_comfy_p5/js/document-export.js';
import {validateGuide,guideMarkdown} from '/extensions/genereti_comfy_agent/js/guide-model.js';
app.registerExtension({name:'Genereti.LessonAuthor',async afterConfigureGraph(){for(const node of app.graph?._nodes??[]){if(node._generetiLessonAutoStart?.()){await node._generetiOperatorRun();break;}}},nodeCreated(node){if(node.comfyClass!=='GeneretiDatLesson')return;ensureControlStyle();const surface=document.createElement('div'),toolbar=document.createElement('div'),preview=document.createElement('ol'),status=document.createElement('span');surface.style.cssText='width:100%;display:flex;flex-direction:column;gap:4px';toolbar.className='genereti-node-controls';preview.style.cssText='margin:0;padding-left:22px;max-height:160px;overflow:auto;font:12px/1.6 system-ui';status.style.cssText='font:11px monospace';let guide,source,last,markdown='',owned=false;const button=(glyph,label,action)=>{const b=document.createElement('button');b.textContent=glyph;b.title=label;b.setAttribute('aria-label',label);b.onclick=action;toolbar.append(b);return b;};
 function update(){const current=window.generetiGuides?.current?.();for(const [i,item] of [...preview.children].entries()){const b=item.firstElementChild;if(b){b.setAttribute('aria-current',String(current&&guide&&current.id===guide.id&&current.index===i?'step':'false'));b.style.background=current&&guide&&current.id===guide.id&&current.index===i?'color-mix(in srgb,currentColor 12%,transparent)':'transparent';}}const text=node.widgets.find(w=>w.name==='guide')?.value;if(text===last)return;last=text;try{guide=validateGuide(JSON.parse(text));markdown=guideMarkdown(guide);source={rows:markdown.split('\n').map(line=>[line])};preview.replaceChildren();for(const [i,step] of guide.steps.entries()){const item=document.createElement('li'),jump=document.createElement('button');jump.textContent=step.title;jump.title='Open this tutorial step';jump.setAttribute('aria-label',`Step ${i+1}: ${step.title}`);jump.style.cssText='font:inherit;color:inherit;border:0;border-radius:4px;background:transparent;text-align:left;cursor:pointer;padding:2px 4px;width:100%';jump.onclick=event=>{event.stopPropagation();return runLesson(i);};item.append(jump);preview.append(item);}status.textContent=`${guide.steps.length} steps · Run starts the learner guide`;run.disabled=false;}catch(error){guide=null;run.disabled=true;status.textContent=error.message;}}
 const runLesson=async(stepIndex=0)=>{try{update();if(!guide)return;if(!window.generetiGuides)throw Error('Install the Genereti agent pack for lesson playback');await window.generetiGuides.list();window.generetiGuides.register(guide);await window.generetiGuides.start(guide.id,stepIndex);owned=true;}catch(error){status.textContent=error.message;}};
 const run=button('▷','Run authored lesson',()=>runLesson());node._generetiOperatorRun=runLesson;
 button('▷▷','Play all recorded steps · stops at manual instructions',async()=>{try{update();if(!guide)return;await window.generetiGuides.list();window.generetiGuides.register(guide);owned=true;await window.generetiGuides.play(guide.id);}catch(error){status.textContent=error.message;}});
 button('■','Stop learner guide',()=>{window.generetiGuides?.stop();owned=false;});
 const recorder=createRecorder(app,node,text=>{status.textContent=text;});
 const record=button('●','Record tutorial actions · append steps to this lesson',()=>{if(recorder.running)return;recorder.start({includeExisting:true});record.setAttribute('aria-pressed','true');});record.setAttribute('aria-pressed','false');
 button('+','New recorded step',()=>{if(recorder.running)recorder.next();});
 button('✓','Stop recording and append steps',()=>{if(!recorder.running)return;const steps=recorder.stop();record.setAttribute('aria-pressed','false');if(!steps.length){status.textContent='No actions recorded';return;}update();const draft=guide??{format:'genereti-guide',version:1,id:'recorded-'+crypto.randomUUID(),title:'Recorded tutorial',summary:'',steps:[]};try{const result=validateGuide({...draft,steps:[...draft.steps,...steps]}),w=node.widgets.find(w=>w.name==='guide');app.graph.beforeChange?.();if(w.options?.setValue)w.options.setValue(JSON.stringify(result,null,2));else w.value=JSON.stringify(result,null,2);node.setDirtyCanvas?.(true,true);app.graph.afterChange?.();update();}catch(error){status.textContent=error.message;}});

 toolbar.append(documentExportControls(()=>{update();if(!guide)throw Error('Correct the lesson JSON before exporting');return {title:guide.title,source:markdown,mode:'markdown'};},error=>status.textContent=error.message));
 button('{}','Export editable lesson JSON',async()=>{try{update();if(!guide)return;const {downloadDocument}=await import('/extensions/genereti_comfy_p5/lib/document.mjs');downloadDocument(JSON.stringify(guide,null,2),guide.id+'.json','application/json');}catch(error){status.textContent=error.message;}});
 const startup=document.createElement('select');startup.title='Tutorial startup when workflow opens';startup.setAttribute('aria-label',startup.title);for(const [value,label] of [['manual','Manual start'],['open','Start on open'],['first','Start if not played']])startup.append(new Option(label,value));startup.value=node.properties.generetiLessonStartup??'manual';startup.onchange=()=>{node.properties.generetiLessonStartup=startup.value;node.setDirtyCanvas?.(true,true);};toolbar.append(startup);const configured=node.onConfigure;node.onConfigure=function(){configured?.apply(this,arguments);startup.value=node.properties.generetiLessonStartup??'manual';};node._generetiLessonAutoStart=()=>{update();return guide&&(startup.value==='open'||startup.value==='first'&&!window.generetiGuides?.hasPlayed(guide.id));};
 const collapse=button('⌄','Minimize lesson outline',()=>{preview.hidden=!preview.hidden;collapse.textContent=preview.hidden?'›':'⌄';collapse.setAttribute('aria-expanded',String(!preview.hidden));node.setSize?.(node.computeSize());});collapse.setAttribute('aria-expanded','true');surface.append(toolbar,preview,status);
 node._generetiDatTable=()=>source;node._generetiLiveValue=slot=>slot===1?markdown:undefined;
 node.addDOMWidget('lesson_toolbar','GENERETI_LESSON_TOOLBAR',surface,{serialize:false,hideOnZoom:false}).computeSize=w=>[w,preview.hidden?60:220];let timer=setInterval(update,200);update();const removed=node.onRemoved;node.onRemoved=function(){clearInterval(timer);recorder.cancel();if(owned)window.generetiGuides?.stop();return removed?.apply(this,arguments);};
}});
