import {app} from '../../scripts/app.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
import {documentExportControls} from '/extensions/genereti_comfy_p5/js/document-export.js';
import {validateGuide,guideMarkdown} from '/extensions/genereti_comfy_agent/js/guide-model.js';
app.registerExtension({name:'Genereti.LessonAuthor',async afterConfigureGraph(){for(const node of app.graph?._nodes??[]){if(node._generetiLessonAutoStart?.()){await node._generetiOperatorRun();break;}}},nodeCreated(node){if(node.comfyClass!=='GeneretiDatLesson')return;ensureControlStyle();const surface=document.createElement('div'),toolbar=document.createElement('div'),preview=document.createElement('ol'),status=document.createElement('span');surface.style.cssText='width:100%;display:flex;flex-direction:column;gap:4px';toolbar.className='genereti-node-controls';preview.style.cssText='margin:0;padding-left:22px;max-height:160px;overflow:auto;font:12px/1.6 system-ui';status.style.cssText='font:11px monospace';let guide,source,last,markdown='',owned=false;const button=(glyph,label,action)=>{const b=document.createElement('button');b.textContent=glyph;b.title=label;b.setAttribute('aria-label',label);b.onclick=action;toolbar.append(b);return b;};
 function update(){const text=node.widgets.find(w=>w.name==='guide')?.value;if(text===last)return;last=text;try{guide=validateGuide(JSON.parse(text));markdown=guideMarkdown(guide);source={rows:markdown.split('\n').map(line=>[line])};preview.replaceChildren();for(const step of guide.steps){const item=document.createElement('li');item.textContent=step.title;preview.append(item);}status.textContent=`${guide.steps.length} steps · Run starts the learner guide`;run.disabled=false;}catch(error){guide=null;run.disabled=true;status.textContent=error.message;}}
 const runLesson=async()=>{try{update();if(!guide)return;if(!window.generetiGuides)throw Error('Install the Genereti agent pack for lesson playback');await window.generetiGuides.list();window.generetiGuides.register(guide);await window.generetiGuides.start(guide.id);owned=true;}catch(error){status.textContent=error.message;}};
 const run=button('▷','Run authored lesson',runLesson);node._generetiOperatorRun=runLesson;
 button('■','Stop learner guide',()=>{window.generetiGuides?.stop();owned=false;});
 toolbar.append(documentExportControls(()=>{update();if(!guide)throw Error('Correct the lesson JSON before exporting');return {title:guide.title,source:markdown,mode:'markdown'};},error=>status.textContent=error.message));
 button('{}','Export editable lesson JSON',async()=>{try{update();if(!guide)return;const {downloadDocument}=await import('/extensions/genereti_comfy_p5/lib/document.mjs');downloadDocument(JSON.stringify(guide,null,2),guide.id+'.json','application/json');}catch(error){status.textContent=error.message;}});
 const startup=document.createElement('select');startup.title='Tutorial startup when workflow opens';startup.setAttribute('aria-label',startup.title);for(const [value,label] of [['manual','Manual start'],['open','Start on open'],['first','Start if not played']])startup.append(new Option(label,value));startup.value=node.properties.generetiLessonStartup??'manual';startup.onchange=()=>{node.properties.generetiLessonStartup=startup.value;node.setDirtyCanvas?.(true,true);};toolbar.append(startup);const configured=node.onConfigure;node.onConfigure=function(){configured?.apply(this,arguments);startup.value=node.properties.generetiLessonStartup??'manual';};node._generetiLessonAutoStart=()=>{update();return guide&&(startup.value==='open'||startup.value==='first'&&!window.generetiGuides?.hasPlayed(guide.id));};
 const collapse=button('⌄','Minimize lesson outline',()=>{preview.hidden=!preview.hidden;collapse.textContent=preview.hidden?'›':'⌄';collapse.setAttribute('aria-expanded',String(!preview.hidden));node.setSize?.(node.computeSize());});collapse.setAttribute('aria-expanded','true');surface.append(toolbar,preview,status);
 node._generetiDatTable=()=>source;node._generetiLiveValue=slot=>slot===1?markdown:undefined;
 node.addDOMWidget('lesson_toolbar','GENERETI_LESSON_TOOLBAR',surface,{serialize:false,hideOnZoom:false}).computeSize=w=>[w,preview.hidden?60:220];let timer=setInterval(update,200);update();const removed=node.onRemoved;node.onRemoved=function(){clearInterval(timer);if(owned)window.generetiGuides?.stop();return removed?.apply(this,arguments);};
}});
