import {guideStyle} from './guide-style.js';
import {app} from '../../../../scripts/app.js';
import {highlightGeometry} from './guide-highlight.js';
import {validateGuide} from './guide-model.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
const library=new Map();let root,halo,active,index=0,baseline,viewBefore,frame,ready,targetRadius;
const button=(label,title,action)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.title=title;b.setAttribute('aria-label',title);b.onclick=action;return b;};
async function load(){ready??=fetch('/extensions/genereti_comfy_agent/lessons/catalog.json').then(r=>{if(!r.ok)throw Error('Lesson catalog unavailable');return r.json();}).then(items=>{for(const item of items)register(item);});return ready;}
function register(input){const guide=validateGuide(input);library.set(guide.id,guide);return guide;}
function target(step){return app.graph?._nodes?.find(n=>n.comfyClass===step.target?.nodeType||n.type===step.target?.nodeType);}
function host(node){return node?document.querySelector(`.lg-node[data-node-id="${CSS.escape(String(node.id))}"]`):null;}
function element(step){const n=target(step),h=host(n);if(!h)return null;switch(step.target.part){case 'code':return h.querySelector('.cm-editor')??h;case 'preview':return h.querySelector('.genereti-preview-actions')?.nextElementSibling??h.querySelector('canvas,table')??h;case 'toolbar':return h.querySelector('.genereti-node-controls,.genereti-livecode-toolbar')??h;case 'parameter':return h;default:return h;}}
function getValue(step){return target(step)?.widgets?.find(w=>w.name===step.target?.widget)?.value;}
function asserted(step){const n=target(step),h=host(n);if(!n)return false;switch(step.check?.kind){case 'changed-widget':return getValue(step)!==baseline;case 'connected-input':return n.inputs?.some(i=>(!step.check.input||i.name===step.check.input)&&i.link!=null);case 'overlay-open':return h?.querySelector('[aria-label^="Close output overlay"]')?.getAttribute('aria-pressed')==='true'||h?.querySelector('[aria-label^="Open output overlay"]')?.getAttribute('aria-pressed')==='true';case 'backdrop-open':return h?.querySelector('[aria-label*="output backdrop"]')?.getAttribute('aria-pressed')==='true';case 'preview-frozen':return h?.querySelector('[aria-label^="Freeze"]')?.getAttribute('aria-pressed')==='true';default:return true;}}
function focus(step){const n=target(step);if(n){app.canvas?.centerOnNode?.(n);app.canvas?.setDirty(true,true);}}
const setting=(id,fallback)=>app.ui.settings.getSettingValue('Genereti.Learning.'+id,fallback);
const validColor=(value,fallback)=>typeof value==='string'&&CSS.supports('color',value)?value:fallback;
function appearance(){
 if(!root)return;const background=setting('PanelBackground','Theme'),custom=setting('PanelColor','#262626'),style=active?guideStyle(active,index):{panel:{frame:{},glow:{}},target:{frame:{},glow:{}}};
 targetRadius=style.target.frame.radius;
 const color=validColor(style.target.frame.color,validColor(setting('HighlightColor','').trim(),'var(--fg-color,#ddd)'));
 const panelBackground=background==='Soft contrast'?'color-mix(in srgb,var(--comfy-menu-bg,#222) 85%,var(--fg-color,#ddd))':background==='Custom'?validColor(custom,'var(--comfy-menu-bg,#222)'):'var(--comfy-menu-bg,#222)';
 for(const [el,surface,panel] of [[root,style.panel,true],[halo,style.target,false]]){
  const frame=surface.frame,glow=surface.glow;el.style.borderColor=validColor(frame.color,panel?'var(--border-color,#555)':color);el.style.borderWidth=(frame.width??(panel?1:2))+'px';
  if(panel)el.style.borderRadius=(frame.radius??8)+'px';
  el.style.background=validColor(surface.backdrop,panel?panelBackground:`color-mix(in srgb,${color} 5%,transparent)`);
  el.style.setProperty('--genereti-glow-color',validColor(glow.color,color));el.style.setProperty('--genereti-glow-radius',(glow.radius??12)+'px');el.style.setProperty('--genereti-glow-spread',(glow.spread??3)+'px');el.style.setProperty('--genereti-glow-duration',(glow.duration??3)+'s');
  const enabled=glow.enabled??!panel,pulse=glow.pulse??setting('HighlightPulse',true);el.classList.toggle('genereti-guide-glow',enabled);el.classList.toggle('genereti-guide-pulse',enabled&&pulse);
 }
}

function animate(){if(!active)return;track();frame=requestAnimationFrame(animate);}
function track(){if(!active)return;const targetEl=element(active.steps[index]),el=targetEl?.matches('.lg-node')?targetEl.firstElementChild??targetEl:targetEl,r=el?.getBoundingClientRect();halo.hidden=!r||r.width<1||r.height<1;if(r){const style=getComputedStyle(el),g=highlightGeometry(r,el.offsetWidth,el.offsetHeight,[style.borderTopLeftRadius,style.borderTopRightRadius,style.borderBottomRightRadius,style.borderBottomLeftRadius]);halo.style.transform=`translate(${g.left}px,${g.top}px)`;halo.style.width=`${g.width}px`;halo.style.height=`${g.height}px`;halo.style.borderRadius=targetRadius===undefined?g.radius:targetRadius+'px';}
 const next=root.querySelector('[data-next]');if(next&&active.steps[index].check&&asserted(active.steps[index])){next.disabled=false;root.querySelector('[data-check-status]').textContent='Check passed';}}
function render(){
 if(!active)return;root.replaceChildren();root.hidden=false;const step=active.steps[index],title=document.createElement('strong');title.textContent=`${active.title} · ${index+1}/${active.steps.length}`;const header=document.createElement('div');header.className='genereti-node-controls';header.style.justifyContent='space-between';draggable(header);header.append(title,button('×','Close guide · learner edits stay',()=>stop()));
 const heading=document.createElement('h3');heading.textContent=step.title;const text=document.createElement('p');text.textContent=step.text;const note=document.createElement('p');note.style.opacity='.7';note.style.fontSize='12px';note.textContent=step.target&&!target(step)?`Add ${step.target.nodeType}, or open the Operators lesson workflow, to try this step.`:'';
 const controls=document.createElement('div');controls.className='genereti-node-controls';const back=button('←','Previous step',()=>move(-1));back.disabled=index===0;controls.append(back,button('◎','Focus this tool',()=>focus(step)));
 const checkStatus=document.createElement('span');checkStatus.dataset.checkStatus='';checkStatus.setAttribute('aria-live','polite');
 if(step.check)controls.append(button('✓','Check learner action',()=>{const passed=asserted(step);checkStatus.textContent=passed?'Check passed':'Try the action, or skip this check';next.disabled=!passed;}),button('↠','Skip this learner check',()=>move(1)));
 const next=button(index===active.steps.length-1?'✓':'→',index===active.steps.length-1?'Finish guide':'Next step',()=>move(1));next.dataset.next='';next.disabled=Boolean(step.check);controls.append(next);
 root.append(header,heading,text,note,checkStatus,controls);appearance();for(const el of [root,halo])for(const animation of el.getAnimations())animation.currentTime=0;focus(step);track();
}
function move(amount){if(index+amount>=active.steps.length){stop();showLibrary();return;}index=Math.max(0,index+amount);baseline=getValue(active.steps[index]);render();}
async function start(id){await load();const guide=library.get(id);if(!guide)throw Error('Unknown guide');stop();mount();active=guide;index=0;viewBefore={scale:app.canvas.ds.scale,offset:[...app.canvas.ds.offset]};baseline=getValue(guide.steps[0]);render();appearance();frame=requestAnimationFrame(animate);window.generetiGuides.markPlayed(guide.id);}
function stop(){cancelAnimationFrame(frame);frame=null;active=null;if(root){root.hidden=true;appearance();}if(halo)halo.hidden=true;if(viewBefore){app.canvas.ds.scale=viewBefore.scale;app.canvas.ds.offset[0]=viewBefore.offset[0];app.canvas.ds.offset[1]=viewBefore.offset[1];app.canvas.setDirty(true,true);viewBefore=null;}}
function clampPanel(){if(!root||!root.style.left)return;const r=root.getBoundingClientRect();root.style.left=Math.max(0,Math.min(parseFloat(root.style.left),innerWidth-r.width))+'px';root.style.top=Math.max(0,Math.min(parseFloat(root.style.top),innerHeight-r.height))+'px';}
function draggable(header){header.style.cursor='move';header.title='Drag to reposition guide';header.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,select'))return;const r=root.getBoundingClientRect(),x=e.clientX,y=e.clientY;header.setPointerCapture(e.pointerId);e.preventDefault();e.stopPropagation();root.style.right=root.style.bottom='auto';const move=e=>{root.style.left=r.left+e.clientX-x+'px';root.style.top=r.top+e.clientY-y+'px';clampPanel();e.stopPropagation();};const end=e=>{header.removeEventListener('pointermove',move);header.removeEventListener('pointerup',end);header.removeEventListener('pointercancel',end);e.stopPropagation();};header.addEventListener('pointermove',move);header.addEventListener('pointerup',end);header.addEventListener('pointercancel',end);});}
function mount(){if(root)return;ensureControlStyle();const style=document.createElement('style');style.textContent='.genereti-guide{position:fixed;right:20px;bottom:24px;z-index:2147483000;box-sizing:border-box;width:min(390px,calc(100vw - 40px));max-height:70vh;overflow:auto;padding:14px;border:1px solid var(--border-color,#555);border-radius:8px;background:var(--comfy-menu-bg,#222);color:var(--fg-color,#ddd);font:14px/1.5 system-ui;box-shadow:0 6px 24px #0004}.genereti-guide[hidden],.genereti-guide-halo[hidden]{display:none}.genereti-guide .genereti-node-controls{font-size:12px}.genereti-guide .genereti-node-controls button{width:auto;min-width:30px;padding:0 8px}.genereti-guide h3{margin:12px 0 4px}.genereti-guide p{white-space:pre-wrap;margin:8px 0}.genereti-guide-halo{left:0;top:0;will-change:transform;position:fixed;z-index:2147482999;pointer-events:none;border:2px solid var(--genereti-highlight,var(--fg-color,#ddd));background:color-mix(in srgb,var(--genereti-highlight,var(--fg-color,#ddd)) 5%,transparent);box-sizing:border-box}.genereti-guide-glow{box-shadow:0 0 var(--genereti-glow-radius,12px) var(--genereti-glow-spread,3px) color-mix(in srgb,var(--genereti-glow-color,#ddd) 35%,transparent)}.genereti-guide-glow.genereti-guide-pulse{animation:genereti-guide-glow var(--genereti-glow-duration,3s) ease-in-out infinite;animation-duration:var(--genereti-glow-duration,3s)!important}@keyframes genereti-guide-glow{0%,100%{box-shadow:0 0 2px .5px color-mix(in srgb,var(--genereti-glow-color,#ddd) 12%,transparent)}50%{box-shadow:0 0 var(--genereti-glow-radius,12px) var(--genereti-glow-spread,3px) color-mix(in srgb,var(--genereti-glow-color,#ddd) 45%,transparent)}}@media(prefers-reduced-motion:reduce){.genereti-guide-glow.genereti-guide-pulse{animation:none!important}}.genereti-guide input{max-width:100%}';document.head.append(style);root=document.createElement('section');root.className='genereti-guide';root.setAttribute('role','region');root.setAttribute('aria-label','OpenTouch learning guide');root.hidden=true;halo=document.createElement('div');halo.className='genereti-guide-halo';halo.hidden=true;document.body.append(halo,root);appearance();window.addEventListener('resize',clampPanel);window.addEventListener('keydown',e=>{if(e.code==='Escape'&&!root.hidden){stop();e.preventDefault();}},true);}
async function showLibrary(){try{await load();stop();mount();root.hidden=false;root.replaceChildren();const header=document.createElement('div');header.className='genereti-node-controls';draggable(header);const title=document.createElement('strong');title.textContent='ꘇ OpenTouch lessons';header.append(title,button('×','Close lessons',stop));root.append(header);
 const note=document.createElement('p');note.textContent='Guides focus real tools and wait for your actions. No device capture, MIDI permission or inference starts automatically.';root.append(note);
 for(const guide of library.values()){const row=document.createElement('div');row.style.margin='12px 0';const name=document.createElement('strong');name.textContent=guide.title;const summary=document.createElement('p');summary.textContent=guide.summary;const controls=document.createElement('div');controls.className='genereti-node-controls';controls.append(button('▶','Start '+guide.title,()=>start(guide.id)));row.append(name,summary,controls);root.append(row);}
 const actions=document.createElement('div');actions.className='genereti-node-controls';actions.append(button('Open lesson workflow','Open a separate temporary lesson tab',async()=>{try{const r=await fetch('/extensions/genereti_comfy_agent/lessons/operators.json');if(!r.ok)throw Error('Lesson workflow unavailable');const graph=await r.json();delete graph.id;await app.loadGraphData(graph,true,true,'OpenTouch lesson '+Date.now(),{openSource:'template'});note.textContent='Lesson opened in its own Comfy tab. Choose a guide to start.';}catch(error){note.textContent=error.message;}}));
 for(const [label,file,id] of [['Open authoring workflow','authoring.json','lesson-authoring'],['Open interactive views workflow','views.json','interactive-output-views']])actions.append(button(label,'Open a separate model-free demo and start its walkthrough',async()=>{try{const r=await fetch('/extensions/genereti_comfy_agent/lessons/'+file);if(!r.ok)throw Error('Lesson workflow unavailable');const graph=await r.json();delete graph.id;await app.loadGraphData(graph,true,true,'ꘇ-'+id+' '+Date.now(),{openSource:'template'});await start(id);}catch(error){note.textContent=error.message;}}));
 const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;input.onchange=async()=>{try{const file=input.files[0];if(file.size>512000)throw Error('Guide file too large');register(JSON.parse(await file.text()));await showLibrary();}catch(error){note.textContent=error.message;}};actions.append(button('Import guide','Import a local genereti-guide JSON · no code execution',()=>input.click()),input);root.append(actions);
 }catch(error){console.error('Genereti guides:',error);}}
const playedKey=id=>'genereti-guide-played:'+id;
window.generetiGuides={hasPlayed:id=>{try{return localStorage.getItem(playedKey(id))==='true';}catch{return false;}},markPlayed:id=>{try{localStorage.setItem(playedKey(id),'true');}catch{}},isActive:()=>Boolean(active),list:async()=>{await load();return [...library.values()];},start,stop,register,open:showLibrary};
app.registerExtension({name:'Genereti.Guides',commands:[{id:'Genereti.OpenGuides',label:'ꘇ OpenTouch lessons',icon:'pi pi-book',function:showLibrary}],settings:[{id:'Genereti.Learning.HighlightColor',name:'Guide highlight color',category:['Genereti','Learning','Appearance'],type:'text',defaultValue:'',onChange:appearance,tooltip:'CSS color for the target outline, background tint and glow. Leave empty for the theme color.'},{id:'Genereti.Learning.HighlightPulse',name:'Pulse guide highlight',category:['Genereti','Learning','Appearance'],type:'boolean',defaultValue:true,onChange:appearance,tooltip:'Gently glow the tutorial target. Respects reduced motion.'},{id:'Genereti.Learning.PanelBackground',name:'Guide panel background',category:['Genereti','Learning','Appearance'],type:'combo',options:['Theme','Soft contrast','Custom'],defaultValue:'Theme',onChange:appearance},{id:'Genereti.Learning.PanelColor',name:'Custom guide panel background color',category:['Genereti','Learning','Appearance'],type:'text',defaultValue:'#262626',onChange:appearance,tooltip:'CSS color used when Guide panel background is Custom.'},{id:'Genereti.Learning.Guides',name:'Interactive lessons',category:['Genereti','Learning','Guides'],defaultValue:null,type:()=>{const container=document.createElement('div');container.append(button('Open lessons','OpenTouch mini guides and document exports',showLibrary));return container;},tooltip:'Guided lessons with real-node focus and learner checks. Export Markdown, HTML or Print / Save as PDF.'}]});
