import {app} from '../../scripts/app.js';
import {FrameMonitor} from './core/monitor.js';
const stats=new FrameMonitor();let raf=0;
function sample(now){if(!document.hidden)stats.frame(now);raf=requestAnimationFrame(sample);}raf=requestAnimationFrame(sample);
const visibility=()=>{stats.reset();};document.addEventListener('visibilitychange',visibility);
const source=e=>{if(!document.hidden)stats.source(String(e.detail.nodeId),performance.now());};window.addEventListener('genereti-live-frame',source);
let observer,longTasksSupported=false;try{observer=new PerformanceObserver(list=>{for(const task of list.getEntries())stats.task(task.startTime,task.duration);});observer.observe({type:'longtask',buffered:false});longTasksSupported=true;}catch{}
window.generetiPerformanceMonitor={read:()=>({...stats.read(performance.now()),visibility:document.hidden?'hidden':'visible',longTasksSupported}),reset:()=>stats.reset(),duration:(name,ms)=>stats.duration(name,performance.now(),ms)};
app.registerExtension({name:'Genereti.PerformanceMonitor',nodeCreated(node){
 if(node.comfyClass!=='GeneretiPerformanceMonitor')return;
 const box=document.createElement('div'),tools=document.createElement('div'),text=document.createElement('pre'),chart=document.createElement('canvas');box.style.cssText='width:100%;color:var(--input-text,#ddd);font:12px monospace';tools.className='genereti-node-controls';chart.width=300;chart.height=48;chart.style.cssText='width:100%;height:48px';text.style.cssText='margin:4px 0;white-space:pre-wrap;font:inherit;line-height:1.5';let frozen=false,latest={},history=[];
 const button=(glyph,tip,run)=>{const b=document.createElement('button');b.textContent=glyph;b.title=b.ariaLabel=tip;b.onclick=run;tools.append(b);return b;};
 const freeze=button('❄','Freeze monitor display · upstream continues',()=>{frozen=!frozen;freeze.setAttribute('aria-pressed',String(frozen));});freeze.setAttribute('aria-pressed','false');button('↺','Reset the five-second measurement window',()=>{stats.reset();history=[];});button('↓','Export measured browser and delivery timing as JSON',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(latest,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ꘇ-performance-monitor.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 box.append(tools,text,chart);
 const update=()=>{if(frozen||!window.generetiPerformance?.ready)return;latest=window.generetiPerformanceMonitor.read();const names=new Map((node.graph?._nodes??[]).map(n=>[String(n.id),n.title]));text.textContent=`Browser ${latest.fps.toFixed(1)} fps · frame ${latest.meanMs.toFixed(1)} ms\np95 ${latest.p95Ms.toFixed(1)} ms · worst ${latest.worstMs.toFixed(1)} ms\n${latest.slowFrames} frames >50 ms · ${longTasksSupported?latest.longTasks+' long tasks':'Long Tasks unavailable'}\n`+latest.sources.map(s=>`${names.get(s.id)??'#'+s.id}: ${s.fps.toFixed(1)} deliveries/s`).join('\n')+`\nTransport tick ${(latest.work.transport?.meanMs??0).toFixed(2)} ms · UI commit ${(latest.work.timeline?.meanMs??0).toFixed(2)} ms\n5 s window · delivery is not GPU/display fps`;history.push(latest.meanMs);if(history.length>60)history.shift();const ctx=chart.getContext('2d');ctx.clearRect(0,0,300,48);ctx.strokeStyle=getComputedStyle(box).color;ctx.lineWidth=1.5;ctx.beginPath();history.forEach((v,i)=>{const x=i*5,y=48-Math.min(48,v/100*48);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();};
 const timer=setInterval(update,1000);queueMicrotask(update);node._generetiLiveValue=slot=>slot===0?latest.fps:slot===1?{channels:Object.fromEntries(['fps','meanMs','p95Ms','worstMs','slowFrames','longTasks'].map(k=>[k,new Float32Array([latest[k]??0])])),sampleRate:1,start:performance.now()/1000}:slot===2?JSON.stringify(latest):undefined;
 node.addDOMWidget('performance_monitor','GENERETI_PERFORMANCE_MONITOR',box,{serialize:false,hideOnZoom:false}).computeSize=w=>[w,210];
 const removed=node.onRemoved;node.onRemoved=function(){clearInterval(timer);return removed?.apply(this,arguments);};
 }});
window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);observer?.disconnect();window.removeEventListener('genereti-live-frame',source);document.removeEventListener('visibilitychange',visibility);},{once:true});
