import {app} from '../../scripts/app.js';
import {PerformanceService} from './service.js';
import {SCALES,quantizeNote} from './core/music.js';
import {resolveTimeValue,parseTimeValue,formatSecondsAsBBU} from './core/timeValue.js';
const service=new PerformanceService(app);window.generetiPerformance=service;
let mounted,floating;
const version=await(await fetch('/extensions/genereti_comfy_performance/lib/version.json',{cache:'no-store'})).json();
const {mountTimeline}=await import(`./lib/timeline.mjs?v=${version.version}`);
const css=document.createElement('link');css.rel='stylesheet';css.href=`/extensions/genereti_comfy_performance/lib/timeline.css?v=${version.version}`;document.head.append(css);
function toggle(){if(document.documentElement.classList.contains('genereti-satori'))document.documentElement.classList.add('genereti-satori-panels');app.extensionManager.command.execute('Workspace.ToggleBottomPanelTab.genereti-timeline');}
// Keep the native tab selection, close control and splitter. The toolbar portal
// uses their empty header space only while our custom panel is mounted.
function mountDock(container){
 const panel=container.closest('.bottom-panel');
 const header=panel?.querySelector('[role="tablist"] > .flex.w-full.justify-between');
 const toolbarHost=header?document.createElement('div'):null;
 if(toolbarHost){toolbarHost.className='genereti-dock-transport';header.insertBefore(toolbarHost,header.lastElementChild);panel.classList.add('genereti-timeline-dock');}
 const dispose=mountTimeline(container,service,{toolbarHost,visible:()=>!panel||panel.querySelector('[role="tab"][id$="_tab_genereti-timeline"]')?.getAttribute('aria-selected')==='true'});
 return()=>{dispose();toolbarHost?.remove();panel?.classList.remove('genereti-timeline-dock');};
}
function button(glyph,title,action){const b=document.createElement('button');b.textContent=glyph;b.title=b.ariaLabel=title;b.style.cssText='border:0;background:transparent;color:inherit;font:inherit;cursor:pointer;padding:5px';b.onclick=action;return b;}
service.openFloating=()=>{if(floating){floating.box.hidden=false;return;}const box=document.createElement('div'),bar=document.createElement('div'),body=document.createElement('div');box.style.cssText='position:fixed;left:5vw;top:65vh;width:90vw;height:30vh;min-height:180px;z-index:1100;resize:both;overflow:hidden;display:flex;flex-direction:column;background:var(--comfy-menu-bg,#222);color:var(--input-text,#ddd);border:1px solid var(--border-color,#444);border-radius:8px;box-shadow:0 8px 35px #0006';bar.style.cssText='display:flex;justify-content:space-between;align-items:center;cursor:move;padding:3px 9px';bar.append('ꘇ Timeline',button('×','Hide floating timeline',()=>box.hidden=true));body.style.cssText='flex:1;min-height:0';box.append(bar,body);document.body.append(box);floating={box,dispose:mountTimeline(body,service,{visible:()=>!box.hidden})};bar.onpointerdown=e=>{if(e.target.tagName==='BUTTON')return;const x=e.clientX,y=e.clientY,r=box.getBoundingClientRect();bar.setPointerCapture(e.pointerId);bar.onpointermove=event=>{box.style.left=Math.max(0,Math.min(innerWidth-80,r.x+event.clientX-x))+'px';box.style.top=Math.max(0,Math.min(innerHeight-40,r.y+event.clientY-y))+'px';};bar.onpointerup=()=>bar.onpointermove=null;};};
const classes=new Set(['GeneretiLivecode','GeneretiP5Sketch','GeneretiTextureExpression','GeneretiTextureNoise','GeneretiChopExpression','GeneretiChopNoise','GeneretiChopOscillator','GeneretiTextureFeedback','GeneretiTextureFeedbackRef']);
function setupNode(node){
 if(node._generetiPerformanceSetup)return;node._generetiPerformanceSetup=true;node.properties??={};node.properties.generetiPerformanceVersion=1;
 const reportWidget=node.comfyClass==='GeneretiPerformanceMonitor'&&node.widgets?.find(w=>w.name==='report');if(reportWidget){reportWidget.type='GENERETI_HIDDEN_MONITOR';reportWidget.computeSize=()=>[0,-4];reportWidget.draw=()=>{};reportWidget.serializeValue=()=>JSON.stringify(window.generetiPerformanceMonitor?.read()??{});}
 const snapshotWidget=node.widgets?.find(w=>w.name==='performance');if(snapshotWidget){snapshotWidget.type='GENERETI_HIDDEN_PERFORMANCE';snapshotWidget.computeSize=()=>[0,-4];snapshotWidget.draw=()=>{};snapshotWidget.serializeValue=()=>JSON.stringify(node.comfyClass==='GeneretiAudioTransport'?(node.widgets?.find(w=>w.name==='clock_name')?.value==='project'?service.queueSnapshot??service.snapshot():service.queueSnapshot?.clocks?.[node.id]??service.transportFor(node).read()):service.queueSnapshot??service.snapshot());}
 for(const widget of node.widgets??[]){if(widget.name==='performance')continue;const serialize=widget.serializeValue;widget.serializeValue=async function(){const base=serialize?await serialize.apply(this,arguments):this.value,snapshot=service.queueSnapshot;if(!snapshot)return base;if(this.name==='parameters'&&node._generetiLivecode?.parameters){const values=node._generetiLivecode.parameters.read(),slots=node.properties?.generetiLivecodeParameters?.slots??{},overrides=snapshot.overrides?.[node.properties?.generetiLessonRef]??{};for(const [name,slot] of Object.entries(slots))if(overrides[`controls.value${slot}`]!==undefined)values[name]=overrides[`controls.value${slot}`];return JSON.stringify(values);}const ref=node.properties?.generetiLessonRef,override=snapshot.overrides?.[ref]?.[this.name];if(override!==undefined)return override;if(this.name==='time'&&service.linked(node)&&typeof base==='number')return snapshot.seconds+base;return base;};}
 if(classes.has(node.comfyClass)){
  node.properties??={};const row=document.createElement('div');row.className='genereti-node-controls';row.style.cssText='display:flex;gap:5px;font-size:12px;color:var(--input-text,#ddd)';const choice=document.createElement('select');choice.title=choice.ariaLabel='Time source · independent of Live / Comfy Queue delivery';choice.style.cssText='border:0;background:transparent;color:inherit;font:inherit';for(const [value,label] of [['free','Free time'],['linked','Project time']]){const o=document.createElement('option');o.value=value;o.textContent=label;choice.append(o);}choice.value=node.properties.generetiTimeMode??'free';choice.onchange=()=>{node.properties.generetiTimeMode=choice.value;service.save();node._generetiPerformanceSeek?.({type:'binding'});node.setDirtyCanvas?.(true,true);};row.append(choice,button('▥','Open project timeline',toggle));node.addDOMWidget('performance_binding','GENERETI_PERFORMANCE_BINDING',row,{serialize:false,hideOnZoom:false}).computeSize=w=>[w,28];const unbind=service.bind(node,event=>node._generetiPerformanceSeek?.(event));const configured=node.onConfigure;node.onConfigure=function(){const result=configured?.apply(this,arguments);choice.value=this.properties?.generetiTimeMode??'free';return result;};const removed=node.onRemoved;node.onRemoved=function(){unbind();return removed?.apply(this,arguments);};
 }
 if(node.comfyClass==='GeneretiPerformanceTimeline'){const row=document.createElement('div');row.className='genereti-node-controls';row.append(button('▥','Open the project timeline',toggle),button('▣','Open a floating timeline',service.openFloating));node.addDOMWidget('timeline_controls','GENERETI_TIMELINE',row,{serialize:false}).computeSize=w=>[w,35];}
 if(node.comfyClass==='GeneretiPerformanceScale'){const row=document.createElement('div');row.className='genereti-node-controls';row.append(button('✓','Set the global musical scale from this node',()=>{const v=Object.fromEntries(node.widgets.map(w=>[w.name,w.value]));service.edit(d=>d.music={...d.music,root:v.root,scale:v.scale,tuning:v.tuning,degrees:SCALES[v.scale]});}));node.addDOMWidget('scale_controls','GENERETI_SCALE',row,{serialize:false}).computeSize=w=>[w,35];node._generetiLiveValue=slot=>slot===0?JSON.stringify({...service.document.music,...Object.fromEntries(node.widgets.filter(w=>['root','scale','tuning'].includes(w.name)).map(w=>[w.name,w.value])),degrees:SCALES[node.widgets.find(w=>w.name==='scale')?.value]}):undefined;}
 if(['GeneretiPerformanceTime','GeneretiAudioTransport','GeneretiPerformanceQuantize'].includes(node.comfyClass)){
  const prior=node._generetiLiveValue;node._generetiLiveValue=slot=>{if(node.comfyClass==='GeneretiAudioTransport'){const s=service.transportFor(node).read();return slot===0?s:slot===1?clockChannels(s):slot===2?s.seconds:slot===3?s.beat:slot===4?JSON.stringify(s):prior?.(slot);}
   if(node.comfyClass==='GeneretiPerformanceQuantize')return node._generetiChop?.latest&&(slot===0?node._generetiChop.latest:slot===1?Object.values(node._generetiChop.latest.channels)[0].at(-1):undefined);
   const i=node.inputs?.findIndex(i=>i.name==='clock'),link=i>=0?node.getInputLink?.(i):null,source=node.graph?.getNodeById(link?.origin_id),s=source?.comfyClass==='GeneretiAudioTransport'?service.transportFor(source).read():source?._generetiLiveValue?.(link?.origin_slot)??service.snapshot(),unit=node.widgets?.find(w=>w.name==='unit')?.value??'seconds';return slot===0?s[unit]??0:slot===1?clockChannels(s):slot===2?JSON.stringify(s):slot===3?s:undefined;};
  const status=document.createElement('div');status.style.cssText='font:11px monospace;opacity:.8;color:var(--input-text,#ddd)';node.addDOMWidget('time_readout','GENERETI_TIME_READOUT',status,{serialize:false}).computeSize=w=>[w,25];
  const refresh=()=>{if(node.comfyClass==='GeneretiPerformanceQuantize'){const i=node.inputs?.findIndex(i=>i.name==='input'),link=i>=0?node.getInputLink?.(i):null,source=node.graph?.getNodeById(link?.origin_id),input=source?._generetiLiveValue?.(link?.origin_slot)??source?._generetiChop?.latest;if(input?.channels){const j=node.inputs.findIndex(i=>i.name==='music'),musicLink=node.getInputLink?.(j),musicSource=node.graph?.getNodeById(musicLink?.origin_id);let m=service.document.music;const text=musicSource?._generetiLiveValue?.(musicLink?.origin_slot)??node.widgets?.find(w=>w.name==='music')?.value;if(text){try{m=JSON.parse(text);}catch{status.textContent='Invalid music JSON';return;}}const output={...input,channels:Object.fromEntries(Object.entries(input.channels).map(([name,data])=>[name,Float32Array.from(data,x=>name.startsWith('note')||Object.keys(input.channels).length===1?quantizeNote(x,m):x)]))};node._generetiChop??={};node._generetiChop.latest=output;status.textContent='Quantized pitches · gates pass through';}}
   else{const slot=node.comfyClass==='GeneretiAudioTransport'?2:0;status.textContent=`${Number(node._generetiLiveValue(slot)).toFixed(3)} · ${node.comfyClass==='GeneretiAudioTransport'?'clock':'live value'}`;}window.dispatchEvent(new CustomEvent('genereti-control-frame',{detail:{nodeId:node.id}}));};const unsub=service.subscribe(refresh);queueMicrotask(()=>{if(service.ready&&node.graph)refresh();});const removed=node.onRemoved;node.onRemoved=function(){unsub();return removed?.apply(this,arguments);};
 }
}
export function clockChannels(s){return {channels:Object.fromEntries(['seconds','quarterNotes','beat','bar','beatInBar','ticks','phase','bpm','playing','iteration'].map(k=>[k,new Float32Array([s[k]])])),sampleRate:25,start:s.seconds};}
app.registerExtension({name:'Genereti.Performance',commands:[{id:'Genereti.ToggleTimeline',label:'ꘇ Timeline',tooltip:'Show / hide the performance timeline. The transport keeps running when hidden.',icon:'pi pi-sliders-h',function:toggle},{id:'Genereti.PlayPauseTransport',label:'ꘇ Play / pause project time',tooltip:'Audio remains explicitly enabled at mod.output.',function:()=>service.clock.read().playing?service.clock.pause():service.clock.play()}],keybindings:[{commandId:'Genereti.ToggleTimeline',combo:{key:'t',alt:true,shift:true}},{commandId:'Genereti.PlayPauseTransport',combo:{key:' ',alt:true}}],bottomPanelTabs:[{id:'genereti-timeline',title:'ꘇ Timeline',type:'custom',render(container){mounted?.();mounted=mountDock(container);},destroy(){mounted?.();mounted=null;}}],nodeCreated:setupNode,beforeConfigureGraph(data){service.ready=false;window.generetiPerformanceMonitor?.reset();const indices={GeneretiTextureNoise:13,GeneretiTextureExpression:4,GeneretiChopExpression:5,GeneretiDatExpression:1,GeneretiLivecode:6};for(const node of data.nodes??[]){if(node.properties?.generetiPerformanceVersion===1)continue;const i=indices[node.type];if(i!==undefined&&Array.isArray(node.widgets_values)&&node.widgets_values.length>i)node.widgets_values.splice(i,0,'{}');node.properties??={};node.properties.generetiPerformanceVersion=1;}service.load(data.extra?.generetiPerformance);},afterConfigureGraph(){service.ready=true;for(const node of app.graph._nodes??[])setupNode(node);},setup(){const original=app.graphToPrompt;app.graphToPrompt=async function(){const previous=service.queueSnapshot;service.queueSnapshot=service.snapshot();service.queueSnapshot.clocks=Object.fromEntries((app.graph._nodes??[]).filter(n=>n.comfyClass==='GeneretiAudioTransport'&&n.widgets?.find(w=>w.name==='clock_name')?.value!=='project').map(n=>[n.id,service.transportFor(n).read()]));service.queueSnapshot.overrides=Object.fromEntries((app.graph._nodes??[]).filter(n=>n._generetiPerformanceValues&&n.properties?.generetiLessonRef).map(n=>[n.properties.generetiLessonRef,{...n._generetiPerformanceValues}]));try{return await original.apply(this,arguments);}finally{service.queueSnapshot=previous;}};}});
window.addEventListener('pagehide',()=>{service.dispose();mounted?.();floating?.dispose();});
// A Genereti-owned facade. Do not replace any unrelated global window.__.
service.api={get time(){return service.clock.read().seconds;},get transport(){return service.snapshot();},get music(){return service.document.music;},timeValue:{resolve:expression=>resolveTimeValue(expression,service.clock.context()),parse:expression=>parseTimeValue(expression,service.clock.context()),format:seconds=>formatSecondsAsBBU(seconds,service.clock.context())},data:{get:name=>service.document.data[name],set:(name,value)=>{if(JSON.stringify(value)?.length>65536)throw Error('Shared value exceeds 64 KB');service.edit(d=>d.data[name]=structuredClone(value));}},musicTools:{quantizeNote:n=>service.quantizeNote(n),frequency:n=>service.frequency(n)}};
