import {app} from '../../scripts/app.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
import {acquireAudio,releaseAudio} from './audio.js';
import {AudioPatch} from './modular-audio.js';
import {pattern,stepTime,events,heldNotes,noteFrame} from './audio-sequence.js';
const states=new Set(),active=new Set();let patch,timer;
function getState(id){return [...states].find(s=>s.node.id===id);}
function values(node){const v=Object.fromEntries((node.widgets??[]).filter(w=>['number','string','boolean'].includes(typeof w.value)).map(w=>[w.name,w.value]));for(let i=0;i<(node.inputs??[]).length;i++){const input=node.inputs[i],link=node.getInputLink?.(i);if(!link||String(input.type).startsWith('GENERETI_'))continue;const source=node.graph?.getNodeById(link.origin_id),value=source?._generetiLiveValue?.(link.origin_slot)??source?.widgets?.find(w=>w.name==='value')?.value;if(value!==undefined)v[input.widget?.name??input.name]=value;}return v;}
function source(node,name){const i=node.inputs?.findIndex(s=>s.name===name),link=i>=0?node.getInputLink?.(i):null;return node.graph?.getNodeById(link?.origin_id);}
function silenceSignal(s){for(const [name,channel] of Object.entries(s.latest?.channels??{}))if(name==='gate'||name==='velocity'||/note\d+$/.test(name))channel.fill(0);}
function silenceSignals(){for(const s of states)silenceSignal(s);}
function stop(state){active.delete(state.node.id);if(state.running)releaseAudio();state.running=false;state.play?.setAttribute('aria-pressed','false');if(state.play)state.play.textContent='▷';if(!active.size){clearInterval(timer);timer=null;patch?.stop();patch=null;silenceSignals();}else tick();state.status.textContent='Audio stopped · start explicitly';}
function tick(){if(!patch)return;try{
 const defs=new Map();for(const s of states){const id=s.node.id;const inputs={};for(const input of s.node.inputs??[])if(input.type==='GENERETI_AUDIO_BUS'){const upstream=source(s.node,input.name);if(upstream)inputs[input.name]=upstream.id;}defs.set(id,{kind:s.kind,settings:values(s.node),inputs});}
 patch.sync(defs,active);const now=patch.ctx.currentTime;
 for(const clock of states)if(clock.kind==='Transport'){const sig=JSON.stringify([values(clock.node),clock.playing]);if(clock.clockSignature!==sig||clock.anchor===undefined){clock.clockSignature=sig;clock.anchor=now+.03;clock.revision=(clock.revision??0)+1;}}
 for(const [id,m] of patch.modules){const state=getState(id);if(m.kind==='Synth'||m.kind==='DrumKit'){
  const upstream=source(state.node,'notes'),seq=getState(upstream?.id);if(seq&&['Sequence','DrumSequence'].includes(seq.kind)){
   const clock=getState(source(seq.node,'clock')?.id),sv=values(seq.node),cv=clock?values(clock.node):{};if(!clock||clock.kind!=='Transport'){patch.clearVoices(id);state.status.textContent='Connect sequence to mod.transport';continue;}
   const signature=JSON.stringify([upstream.id,clock.node.id,sv,cv,clock.playing,clock.revision]);if(state.signature!==signature){patch.clearVoices(id);state.signature=signature;state.nextStep=0;}if(!clock.playing){silenceSignal(seq);state.status.textContent='Transport paused';continue;}
   clock.anchor??=now+.03;const rows=pattern(sv.pattern,seq.kind==='DrumSequence'),division=Number(sv.division),seconds=60/Number(cv.bpm)/division;
   // On a stalled UI skip missed beats: never burst a backlog of old notes.
   if(stepTime(state.nextStep,clock.anchor,cv.bpm,division,cv.swing)<now-.1)state.nextStep=Math.max(0,Math.ceil((now-clock.anchor)/seconds));
   let count=0;while(stepTime(state.nextStep,clock.anchor,cv.bpm,division,cv.swing)<now+.12&&count++<32){const time=stepTime(state.nextStep,clock.anchor,cv.bpm,division,cv.swing);for(const e of events(rows,state.nextStep,time,seconds*Number(sv.gate??.5),Number(sv.velocity)))patch.trigger(id,e.note,e.time,e.duration,e.velocity);seq.step=state.nextStep++;}
   const currentStep=Math.max(0,Math.floor((now-clock.anchor)/seconds));seq.latest=noteFrame(rows,currentStep,now>=clock.anchor&&((now-clock.anchor)/seconds)%1<Number(sv.gate??.5),Number(sv.velocity),now,1/seconds);if(now-(seq.lastPaint??0)>.1){seq.paint?.(currentStep);seq.lastPaint=now;}patch.setHeld(id,[...state.manual.values()]);state.status.textContent='Routed audio · scheduled on audio clock';
  }else{state.signature=null;const data=upstream?._generetiMusic?.latest??upstream?._generetiChop?.latest??upstream?._generetiDatSignal?.();patch.setHeld(id,[...heldNotes(data),...state.manual.values()]);state.status.textContent='Routed audio · notes / keyboard';}
 }if(m.kind==='Output'){const meter=patch.meter(id);state.meter.value=Math.min(1,meter.peak);state.status.textContent=`Audio running · peak ${meter.peak.toFixed(2)}${meter.peak>.95?' · reduce level':''}`;}}
 }catch(error){for(const id of active){const state=getState(id);state.status.textContent=error.message;}patch.stop();}}
function widgetValue(node,name,value){const w=node.widgets?.find(w=>w.name===name);if(w){w.value=value;w.callback?.(value);node.setDirtyCanvas?.(true,true);}}
function button(label,title,action){const b=document.createElement('button');b.textContent=label;b.title=title;b.setAttribute('aria-label',title);b.onclick=action;return b;}
app.registerExtension({name:'Genereti.ModularAudio',nodeCreated(node){if(!node.comfyClass?.startsWith('GeneretiAudio'))return;ensureControlStyle();const kind=node.comfyClass.slice('GeneretiAudio'.length),surface=document.createElement('div'),tools=document.createElement('div'),status=document.createElement('div');surface.className='genereti-audio-surface';surface.style.cssText='width:100%;display:flex;flex-direction:column;gap:6px;padding:4px 0;color:var(--input-text)';tools.className='genereti-node-controls';status.style.cssText='font-size:11px;opacity:.8';surface.append(tools,status);const state={node,kind,status,manual:new Map(),playing:true,running:false};states.add(state);
 if(kind==='Output'){state.play=button('▷','Start / stop browser audio',async()=>{if(state.running){stop(state);return;}state.play.disabled=true;try{const ctx=await acquireAudio();if(!states.has(state)){releaseAudio();return;}if(!patch){patch=new AudioPatch(ctx);for(const s of states){s.anchor=undefined;s.signature=null;}}state.running=true;active.add(node.id);state.play.textContent='Ⅱ';state.play.setAttribute('aria-pressed','true');tick();timer??=setInterval(tick,25);}catch(error){status.textContent=error.message;}finally{state.play.disabled=false;}});state.play.setAttribute('aria-pressed','false');state.meter=document.createElement('meter');state.meter.min=0;state.meter.max=1;state.meter.style.cssText='width:100%;height:10px;accent-color:var(--input-text)';tools.append(state.play,button('■','Panic · stop all audio outputs',()=>{for(const id of [...active])stop(getState(id));}));surface.append(state.meter);status.textContent='Audio stopped · press ▷ to start';}
 else if(kind==='Transport'){const play=button('Ⅱ','Pause / resume transport',()=>{state.playing=!state.playing;state.anchor=undefined;play.textContent=state.playing?'Ⅱ':'▷';play.setAttribute('aria-pressed',String(state.playing));status.textContent=state.playing?'Transport armed · start mod.output':'Transport paused';});play.setAttribute('aria-pressed','true');tools.append(play,button('↶','Reset shared transport',()=>{state.anchor=undefined;for(const s of states)s.signature=null;}));status.textContent='Transport armed · start mod.output';}
 else if(kind==='Sequence'||kind==='DrumSequence'){
  const grid=document.createElement('div');grid.style.cssText='display:grid;gap:3px;grid-template-columns:repeat(16,minmax(0,1fr));';surface.append(grid);let lastPattern;state.paint=step=>{for(const cell of grid.children)cell.style.background=Number(cell.dataset.step)===step%(Number(cell.dataset.length)||16)?'color-mix(in srgb, var(--input-text) 22%, transparent)':'transparent';};
  const rebuild=()=>{const text=values(node).pattern;if(text===lastPattern)return;lastPattern=text;grid.replaceChildren();try{const rows=pattern(text,kind==='DrumSequence');for(const row of rows)for(let i=0;i<row.steps.length;i++){
   const cell=kind==='Sequence'?document.createElement('input'):button(row.steps[i]?'●':'·',`${row.name} step ${i+1}`,()=>{row.steps[i]=row.steps[i]?0:1;widgetValue(node,'pattern',rows.map(r=>`${r.name}:${r.steps.join('')}`).join(';'));lastPattern=null;rebuild();});cell.dataset.step=i;cell.dataset.length=row.steps.length;cell.style.cssText='min-width:0;width:100%;height:25px;border:0;border-radius:3px;color:inherit;background:transparent;text-align:center;padding:0;font:10px monospace;';if(kind==='Sequence'){cell.value=row.steps[i]<0?'-':row.steps[i];cell.setAttribute('aria-label',`MIDI pitch step ${i+1}, or - for rest`);cell.oninput=()=>{const n=cell.value==='-'?-1:Number(cell.value);if(!cell.value||!Number.isFinite(n)||n< -1||n>127){cell.setCustomValidity('Use MIDI pitch 0..127 or -');return;}cell.setCustomValidity('');row.steps[i]=n;lastPattern=row.steps.map(n=>n<0?'-':n).join(' ');widgetValue(node,'pattern',lastPattern);};}grid.append(cell);}
  status.textContent=kind==='Sequence'?'MIDI pitches · - is a rest':'Rows: kick / snare / hi-hat';}catch(error){status.textContent=error.message;}};state.rebuild=rebuild;queueMicrotask(rebuild);
  state.latest=null;node._generetiDatSignal=()=>state.latest;node._generetiChop=state;
 }else if(kind==='Synth'||kind==='DrumKit'){
  const notes=kind==='Synth'?[60,62,64,65,67,69,71,72]:[36,38,42];for(const note of notes){const b=button(kind==='Synth'?String(note):({36:'Kick',38:'Snare',42:'Hat'})[note],'Audition · requires mod.output Start',()=>{});b.onpointerdown=e=>{e.stopPropagation();b.setPointerCapture(e.pointerId);if(kind==='DrumKit')patch?.trigger(node.id,note,patch.ctx.currentTime,.2,.75);else{state.manual.set(`key${note}`,{key:`key${note}`,note,velocity:.75});if(patch)patch.setHeld(node.id,[...state.manual.values()]);}};const up=()=>{state.manual.delete(`key${note}`);};b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;tools.append(b);}status.textContent='Connect audio bus to mod.output · then Start';
 }else if(kind==='Mixer'){
  const strips=document.createElement('div');strips.style.cssText='display:grid;grid-template-columns:repeat(4,1fr);gap:8px';for(let i=1;i<=4;i++){const strip=document.createElement('div'),label=document.createElement('div'),slider=document.createElement('input'),mute=button('M',`Mute channel ${i}`,()=>widgetValue(node,`mute_${i}`,!values(node)[`mute_${i}`])),solo=button('S',`Solo channel ${i}`,()=>widgetValue(node,`solo_${i}`,!values(node)[`solo_${i}`]));label.textContent=`${i}`;slider.type='range';slider.min=0;slider.max=2;slider.step=.01;slider.setAttribute('aria-label',`Channel ${i} gain`);slider.style.cssText='width:100%;accent-color:var(--input-text)';slider.oninput=()=>widgetValue(node,`level_${i}`,Number(slider.value));strip.append(label,slider,mute,solo);strips.append(strip);(state.controls??=[]).push({i,slider,mute,solo});}surface.append(strips);status.textContent='Four audio buses · faders mirror regular parameters';
 }else status.textContent='Live audio bus · no queue PCM copies';
 const height=kind==='DrumSequence'?126:kind==='Mixer'?114:kind==='Sequence'?76:kind==='Output'?76:62;node.addDOMWidget('audio_controls','GENERETI_AUDIO_CONTROLS',surface,{serialize:false,hideOnZoom:false}).computeSize=w=>[w,height];
 const configured=node.onConfigure;node.onConfigure=function(){const r=configured?.apply(this,arguments);queueMicrotask(()=>state.rebuild?.());return r;};const changed=node.onWidgetChanged;node.onWidgetChanged=function(){const r=changed?.apply(this,arguments);state.rebuild?.();return r;};
 const removed=node.onRemoved;node.onRemoved=function(){stop(state);states.delete(state);return removed?.apply(this,arguments);};
 state.refresh=setInterval(()=>{state.rebuild?.();if(state.controls){const v=values(node);for(const c of state.controls){if(document.activeElement!==c.slider)c.slider.value=v[`level_${c.i}`];c.mute.setAttribute('aria-pressed',String(v[`mute_${c.i}`]));c.solo.setAttribute('aria-pressed',String(v[`solo_${c.i}`]));}}},200);const remove=node.onRemoved;node.onRemoved=function(){clearInterval(state.refresh);return remove?.apply(this,arguments);};
}});
window.addEventListener('pagehide',()=>{for(const id of [...active])stop(getState(id));});
