import {app} from '../../scripts/app.js';
import {ensureControlStyle} from '/extensions/genereti_comfy_p5/js/control-style.js';
import {musicalSignal,noteControl} from './music-signals.js';
import {acquireAudio,releaseAudio,Instrument} from './audio.js';
const states=new Set();let raf;
function values(node){const v=Object.fromEntries((node.widgets??[]).filter(w=>['number','string','boolean'].includes(typeof w.value)).map(w=>[w.name,w.value]));for(let i=0;i<node.inputs.length;i++){const input=node.inputs[i],link=node.getInputLink?.(i);if(!link||input.type==='GENERETI_CHOP')continue;const source=node.graph?.getNodeById(link.origin_id),value=source?._generetiLiveValue?.(link.origin_slot)??source?.widgets?.find(w=>w.name==='value')?.value;if(value!==undefined)v[input.widget?.name??input.name]=value;}return v;}
function source(node){const i=node.inputs.findIndex(s=>s.name==='input'),l=i>=0?node.getInputLink?.(i):null;return node.graph?.getNodeById(l?.origin_id);}
function clock(now){raf=null;const done=new Set(),visiting=new Set();function run(s){if(!s||s.dead||done.has(s))return;if(visiting.has(s))throw Error('Music control cycles are not supported');visiting.add(s);s.update(now,run);visiting.delete(s);done.add(s);}for(const s of states)try{run(s);}catch(e){s.status.textContent=e.message;s.stop();visiting.clear();}if(states.size)raf=requestAnimationFrame(clock);}
app.registerExtension({name:'Genereti.Music',nodeCreated(node){if(!node.comfyClass?.startsWith('GeneretiMusic'))return;ensureControlStyle();const kind=node.comfyClass.slice(13),endpoint=['Synth','DrumKit'].includes(kind),surface=document.createElement('div'),tools=document.createElement('div'),status=document.createElement('span');surface.style.cssText='width:100%;display:flex;flex-direction:column;gap:4px';tools.className='genereti-node-controls';status.style.cssText='font:11px monospace';const play=document.createElement('button');play.textContent=endpoint?'▷':'Ⅱ';play.title=endpoint?'Start / stop browser audio · explicit start':'Pause / resume musical controls';play.setAttribute('aria-label',play.title);play.setAttribute('aria-pressed','false');tools.append(play);surface.append(tools,status);
 const state={node,status,dead:false,running:!endpoint,latest:null,instrument:null,stop(){state.running=false;state.instrument?.stop();if(state.instrument)releaseAudio();state.instrument=null;play.textContent=endpoint?'▷':'▶';play.setAttribute('aria-pressed','false');status.textContent=endpoint?'Audio stopped · Queue never plays sound':'Controls paused';},update(now,run){if(!state.running)return;const v=values(node),upstream=source(node);run(upstream?._generetiMusic);const input=upstream?._generetiMusic?.latest??upstream?._generetiChop?.latest??upstream?._generetiDatSignal?.();if(endpoint){if(!input){state.instrument?.update({gate:false,note:60,velocity:0},v);status.textContent='Connect note/gate/velocity CHOP';return;}state.latest=input;state.instrument?.update(noteControl(input),v);}else{const time=now/1000;if(state.nextTime!==undefined&&time<state.nextTime)return;const start=state.nextTime===undefined||time-state.nextTime>.5?time:state.nextTime;state.nextTime=start+Number(v.samples)/Number(v.sample_rate);state.latest=musicalSignal(kind,v,start+Number(v.time),input);}
 window.dispatchEvent(new CustomEvent('genereti-control-frame',{detail:{nodeId:node.id}}));if(now-(state.lastPaint??0)>100){const n=noteControl(state.latest);status.textContent=`note ${n.note.toFixed(0)} · gate ${Number(n.gate)} · velocity ${n.velocity.toFixed(2)}${endpoint?' · browser audio':''}`;state.lastPaint=now;}
 }};
 play.onclick=async()=>{if(state.running){state.stop();return;}play.disabled=true;try{if(endpoint){const context=await acquireAudio();if(state.dead){releaseAudio();return;}state.instrument=new Instrument(context,kind==='DrumKit');}state.running=true;state.nextTime=undefined;play.textContent='Ⅱ';play.setAttribute('aria-pressed','true');}catch(error){status.textContent=error.message;}finally{play.disabled=false;}};
 status.textContent=endpoint?'Audio stopped · press ▷ to start':'Musical control generator';node._generetiMusic=state;node._generetiDatSignal=()=>state.latest;node._generetiLiveValue=slot=>slot===1?Object.values(state.latest?.channels??{})[0]?.at(-1):undefined;
 node.addDOMWidget('music_preview','GENERETI_MUSIC_PREVIEW',surface,{serialize:false,hideOnZoom:false}).computeSize=w=>[w,62];states.add(state);if(!raf)raf=requestAnimationFrame(clock);const pagehide=()=>state.stop();window.addEventListener('pagehide',pagehide);const removed=node.onRemoved;node.onRemoved=function(){state.dead=true;state.stop();states.delete(state);window.removeEventListener('pagehide',pagehide);if(!states.size){cancelAnimationFrame(raf);raf=null;}return removed?.apply(this,arguments);};
}});
