import {app} from '../../../scripts/app.js';
import {api} from '../../../scripts/api.js';
import {colorPicker} from './color-picker.js';
import {publishLive} from './live-runtime.js';
import {SETTINGS_GLYPH} from './control-style.js';
import {createEditor,examples,defaultAppearance,appearanceValues} from '../lib/editor.mjs';
if(!document.getElementById('genereti-livecode-style')){const style=document.createElement('style');style.id='genereti-livecode-style';style.textContent=`
.genereti-livecode-toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:4px;position:relative;flex-shrink:0}
.genereti-livecode-toolbar .livecode-action{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;flex:none;width:30px;height:30px;min-width:30px;margin:0;padding:0;border:0!important;border-radius:6px;background:transparent;color:inherit;font:inherit;cursor:pointer;list-style:none;vertical-align:middle}
.genereti-livecode-toolbar .livecode-action svg{display:block;width:18px;height:18px;flex:none}
.genereti-livecode-toolbar .livecode-action:hover,.genereti-livecode-toolbar .livecode-action[aria-pressed=true],.genereti-livecode-toolbar details[open]>.livecode-action{background:color-mix(in srgb,currentColor 12%,transparent)}
.genereti-livecode-toolbar .livecode-action:focus-visible{outline:2px solid currentColor;outline-offset:1px}
.genereti-livecode-toolbar select{height:30px;border:0!important;border-radius:6px;box-shadow:none;background:transparent;color:inherit;font:inherit;padding:0 7px;cursor:pointer}
.genereti-livecode-toolbar select:hover{background:color-mix(in srgb,currentColor 8%,transparent)}
.genereti-livecode-toolbar details{position:relative}
.genereti-livecode-toolbar .livecode-export-menu{position:absolute;top:34px;left:0;z-index:15;min-width:160px;padding:4px;border-radius:6px;background:var(--comfy-input-bg,#222);box-shadow:0 4px 16px #0004}
.genereti-livecode-toolbar .livecode-export-menu button{display:block;width:100%;height:30px;padding:0 10px;border:0;border-radius:4px;background:transparent;color:inherit;text-align:left;cursor:pointer}
.genereti-livecode-toolbar .livecode-export-menu button:hover{background:color-mix(in srgb,currentColor 12%,transparent)}
.genereti-livecode [role=tab][aria-selected=true]{background:color-mix(in srgb,currentColor 12%,transparent)!important}
.genereti-livecode summary::-webkit-details-marker{display:none}
.lg-node:has(.genereti-livecode) .mt-auto .rounded-full.bg-component-node-widget-background{display:none}
.genereti-livecode-stage:fullscreen{width:100vw!important;height:100vh!important;max-height:none!important;aspect-ratio:auto!important}
`;document.head.append(style);}
const glyph=paths=>`<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`;
function iconButton(button,label,paths){button.type='button';button.className='livecode-action';button.setAttribute('aria-label',label);button.innerHTML=glyph(paths);}

let libraries;
async function loadLibraries(){return libraries ||= Promise.all(['p5.min.js','lib/runtime.txt'].map(async file=>{const response=await fetch(`/extensions/genereti_comfy_p5/${file}`);if(!response.ok)throw Error(`Livecode library unavailable: ${file}`);return response.text();}));}
const value=(node,name)=>node.widgets.find(w=>w.name===name)?.value;
function editorWidget(node,name){
 const container=document.createElement('div');container.className='genereti-livecode';container.style.cssText='display:flex;flex-direction:column;gap:6px;width:100%;min-height:220px;overflow:visible;background:var(--comfy-input-bg,#171b22);color:var(--fg-color,#eee)';
 const tools=document.createElement('div'),run=document.createElement('button'),stop=document.createElement('button'),status=document.createElement('div'),code=document.createElement('div'),stage=document.createElement('div');
 stage.className='genereti-livecode-stage';iconButton(run,'Run','<path d="m8 5 11 7-11 7Z" fill="currentColor" stroke="none"/>');run.title='Evaluate (Cmd/Ctrl+Enter)';iconButton(stop,'Stop','<rect x="5" y="5" width="14" height="14" rx="1" fill="currentColor" stroke="none"/>');stop.title='Stop · keep last frame (Ctrl+.)';tools.className='genereti-livecode-toolbar';tools.append(run,stop);
 const autoToggle=document.createElement('button');iconButton(autoToggle,'Auto-update','<path d="M20 7h-5V2M4 17h5v5"/><path d="M19 7a8 8 0 0 0-13-2M5 17a8 8 0 0 0 13 2"/>');autoToggle.title='Auto-update code';tools.append(autoToggle);
 function syncAutoUpdate(){const widget=node.widgets.find(w=>w.name==='auto_update');if(!widget)return;widget.options={...widget.options,hidden:true};widget.computeSize=()=>[0,-4];autoToggle.setAttribute('aria-pressed',String(!!widget.value));if(!widget._livecodeToggle){const callback=widget.callback;widget.callback=function(){const result=callback?.apply(this,arguments);syncAutoUpdate();return result;};widget._livecodeToggle=true;}}
 autoToggle.onclick=()=>{const widget=node.widgets.find(w=>w.name==='auto_update');if(!widget)return;widget.value=!widget.value;widget.callback?.(widget.value);syncAutoUpdate();if(!widget.value)clearTimeout(timer);};
 status.style.cssText='font-size:11px;white-space:pre-wrap;max-height:72px;overflow:auto;flex-shrink:0';stage.style.cssText='position:relative;width:100%;aspect-ratio:1;height:0;min-height:0;overflow:hidden;background:#111;flex:1 1 0';container.append(tools,code,status,stage);
 const inputs=new Map();
 const settings={...defaultAppearance,...node.properties.generetiLivecodeAppearance};
 let customThemes={};try{customThemes=JSON.parse(localStorage.getItem('genereti-livecode-themes')||'{}');}catch{}if(!customThemes||typeof customThemes!=='object'||Array.isArray(customThemes))customThemes={};Object.assign(customThemes,node.properties.generetiLivecodeThemes||{});
 const options=document.createElement('details');const summary=document.createElement('summary');summary.className='livecode-action';summary.innerHTML=SETTINGS_GLYPH;summary.title='Settings';summary.setAttribute('aria-label','Settings');options.append(summary);tools.append(options);
 options.style.cssText='position:relative';const settingsPanel=document.createElement('div');settingsPanel.style.cssText='position:absolute;top:32px;left:0;z-index:12;width:300px;max-width:75vw;padding:12px;border:1px solid var(--border-color,#555);border-radius:5px;background:var(--comfy-input-bg,#222);color:var(--fg-color,#eee)';options.append(settingsPanel);const tabs=document.createElement('div');tabs.style.cssText='display:flex;gap:4px;margin-bottom:12px';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Livecode settings');settingsPanel.append(tabs);const controls=document.createElement('div');controls.style.cssText='display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px';controls.setAttribute('role','tabpanel');settingsPanel.append(controls);
 function field(label,key,type,choices){const box=document.createElement('label');box.textContent=label;box.style.cssText='display:grid;gap:4px;min-width:0;font-size:11px';if(type==='color'){box.style.cssText='display:flex;align-items:center;justify-content:space-between;min-width:0;font-size:11px';const picker=colorPicker(settings[key]??appearanceValues(settings)[key],val=>{settings[key]=val;saveAppearance();});inputs.set(key,picker);box.append(picker.element);paletteControls.append(box);return picker;}const input=document.createElement(choices?'select':'input');if(choices)for(const [text,val] of choices){const opt=new Option(text,val);input.append(opt);}else input.type=type;input.value=settings[key]??appearanceValues(settings)[key]??'';inputs.set(key,input);if(type==='number'){input.min=key==='fontSize'?9:1;input.max=key==='fontSize'?36:2.5;input.step=key==='fontSize'?1:.05;input.style.width='100%';}input.style.cssText+=';width:100%;min-width:0;box-sizing:border-box;height:28px';box.append(input);controls.append(box);input.oninput=()=>{settings[key]=type==='number'?Number(input.value):input.value;if(key==='theme')resetColors();else saveAppearance();};return input;}
 const themeSelect=field('Theme','theme','text',[['Dark','dark'],['Light','light'],['Midnight','midnight'],['Paper','paper'],['Mono dark','mono-dark'],['Mono light','mono-light'],['Transparent dark','transparent-dark'],['Transparent light','transparent-light']]);themeSelect.setAttribute('aria-label','Editor theme');themeSelect.oninput=()=>{const selected=themeSelect.value;if(customThemes[selected])Object.assign(settings,customThemes[selected]);settings.theme=selected;if(selected.startsWith('transparent-'))settings.overlayBackground='transparent';syncAppearance();resetColors();};
 const savedGroup=document.createElement('optgroup');savedGroup.label='Saved';themeSelect.append(savedGroup);function refreshThemes(){savedGroup.replaceChildren();for(const id of Object.keys(customThemes))savedGroup.append(new Option(id.replace(/^custom:/,''),id));themeSelect.value=settings.theme;}refreshThemes();
 field('Font','fontFamily','text',[['System mono',defaultAppearance.fontFamily],['Menlo','Menlo, monospace'],['Monaco','Monaco, monospace'],['Courier','"Courier New", monospace'],['System sans','system-ui, sans-serif']]);
 field('Size','fontSize','number');field('Line height','lineHeight','number');
 const paletteDetails=document.createElement('details');paletteDetails.style.gridColumn='1 / -1';const paletteSummary=document.createElement('summary');paletteSummary.textContent='Colors';paletteSummary.style.cssText='cursor:pointer;font-size:11px;padding:4px 0';const paletteControls=document.createElement('div');paletteControls.style.cssText='display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding-top:8px';paletteDetails.append(paletteSummary,paletteControls);controls.append(paletteDetails);
 for(const [label,key] of [['Text','foreground'],['Background','background'],['Keywords','keyword'],['Strings','string'],['Numbers','number'],['Comments','comment'],['Selection','selection'],['Active line','activeLine'],['Brackets','bracket'],['Word matches','selectionMatch'],['Search matches','searchMatch'],['Popup background','popupBackground'],['Popup text','popupText']])field(label,key,'color');
 const reset=document.createElement('button');reset.textContent='Reset colors';reset.onclick=resetColors;function resetColors(){delete settings.dark;for(const key of ['foreground','background','keyword','string','number','comment','selection','activeLine','bracket','selectionMatch','searchMatch','popupBackground','popupText']){delete settings[key];if(customThemes[settings.theme]?.[key])settings[key]=customThemes[settings.theme][key];}if(customThemes[settings.theme])settings.dark=customThemes[settings.theme].dark;for(const [key,input] of inputs)if(input.type==='color')input.value=appearanceValues(settings)[key];saveAppearance();}reset.style.gridColumn='1 / -1';paletteControls.append(reset);
 const css=document.createElement('textarea');css.placeholder='Preview CSS (animations, layout, fonts)';css.title='Preview CSS';css.value=settings.css||'';css.rows=2;css.style.cssText='width:100%;box-sizing:border-box;grid-column:1 / -1';css.oninput=()=>{settings.css=css.value;saveAppearance();};controls.append(css);
 const wrap=document.createElement('input');wrap.type='checkbox';wrap.checked=settings.wrap;const wrapLabel=document.createElement('label');wrapLabel.append(wrap,' Wrap');controls.append(wrapLabel);wrap.onchange=()=>{settings.wrap=wrap.checked;saveAppearance();};
 for(const [label,key] of [['Autocomplete','autocomplete'],['Hover docs','hoverDocs']]){const input=document.createElement('input');input.type='checkbox';input.checked=settings[key]!==false;input.setAttribute('aria-label',label);inputs.set(key,input);const box=document.createElement('label');box.style.fontSize='11px';box.append(input,' '+label);controls.append(box);input.onchange=()=>{settings[key]=input.checked;saveAppearance();};}
 field('Overlay background','overlayBackground','text',[['Transparent','transparent'],['Text only','glyphs'],['Solid','solid']]);
 field('Backdrop opacity','overlayOpacity','number').oninput=function(){settings.overlayOpacity=Math.max(0,Math.min(1,Number(this.value)));saveAppearance();};inputs.get('overlayOpacity').min=0;inputs.get('overlayOpacity').max=1;
 const themeName=document.createElement('input');themeName.type='text';themeName.placeholder='Theme name';themeName.maxLength=48;themeName.setAttribute('aria-label','Custom theme name');themeName.style.cssText='width:100%;min-width:0;box-sizing:border-box;height:28px';const saveTheme=document.createElement('button');saveTheme.type='button';saveTheme.textContent='Save theme';saveTheme.onclick=()=>{const name=themeName.value.trim();if(!name){themeName.focus();return;}const id='custom:'+name;customThemes[id]={...appearanceValues(settings),dark:settings.dark??['dark','midnight','mono-dark','transparent-dark'].includes(settings.theme)};node.properties.generetiLivecodeThemes={...customThemes};try{localStorage.setItem('genereti-livecode-themes',JSON.stringify(customThemes));}catch{}settings.theme=id;refreshThemes();saveAppearance();themeName.value='';};const themeSaveRow=document.createElement('div');themeSaveRow.style.cssText='grid-column:1 / -1;display:flex;gap:6px';themeName.style.flex='1';saveTheme.style.cssText='height:28px;white-space:nowrap;padding:3px 8px';themeSaveRow.append(themeName,saveTheme);controls.append(themeSaveRow);
 function syncAppearance(){for(const [key,input] of inputs)input.value=settings[key]??appearanceValues(settings)[key];for(const key of ['autocomplete','hoverDocs'])inputs.get(key).checked=settings[key]!==false;if(typeof css!=='undefined')css.value=settings.css||'';if(typeof wrap!=='undefined')wrap.checked=settings.wrap;}
 const show=document.createElement('select');for(const [label,mode] of [['Split','both'],['Overlay','overlay'],['Code','code'],['Output','output']])show.append(new Option(label,mode));show.title='Code / output view';show.value=node.properties.generetiLivecodeView||'both';tools.append(show);show.onchange=()=>{node.properties.generetiLivecodeView=show.value;applyView();};
 const exportMenu=document.createElement('details'),exportSummary=document.createElement('summary');exportSummary.className='livecode-action';exportSummary.title='Export';exportSummary.setAttribute('aria-label','Export');exportSummary.innerHTML=glyph('<path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/>');const exportChoices=document.createElement('div');exportChoices.className='livecode-export-menu';exportMenu.append(exportSummary,exportChoices);tools.append(exportMenu);
 function exportChoice(label,tip){const button=document.createElement('button');button.type='button';button.textContent=label;button.title=tip;button.addEventListener('click',()=>exportMenu.open=false);exportChoices.append(button);return button;}
 const png=exportChoice('PNG','Rendered output image'),html=exportChoice('HTML','Standalone page with the last working runtime'),json=exportChoice('JSON','Code and node settings as a JSON object'),script=exportChoice('Source script','Current draft in its language format');
 const indent=document.createElement('button');iconButton(indent,'Format document','<path d="M9 4H7v5l-3 3 3 3v5h2M15 4h2v5l3 3-3 3v5h-2"/>');indent.title='Format document (Cmd/Ctrl+Shift+F)';indent.onclick=()=>formatDocument();const minify=document.createElement('button');iconButton(minify,'Minify','<path d="M4 5v14M20 5v14m-9-7H6m3-3-3 3 3 3m4-3h5m-3-3 3 3-3 3"/>');minify.title='Minify JavaScript · undo to restore';minify.onclick=()=>formatDocument(true);tools.append(indent,minify);show.style.cssText='width:88px';

 async function formatDocument(compact=false){
  const editor=view,source=editor.state.doc.toString(),mode=value(node,'language')||'p5';
  try{if(mode==='glsl'&&!compact){editor.reindent();return;}const formatter=await import('../lib/formatter.mjs');const result=await(compact?formatter.minifySource(source,mode):formatter.formatSource(source,mode));if(editor!==view||editor.state.doc.toString()!==source){status.textContent='Draft changed · format again';return;}editor.replaceDocument(result);status.textContent=compact?'Minified':'Formatted';}catch(error){status.textContent=`Format: ${error.message}`;}
 }
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 png.onclick=async()=>{try{const data=await captureDataUrl();download(await(await fetch(data)).blob(),'genereti-livecode.png');}catch(error){status.textContent=error.message;}};
 html.onclick=async()=>{try{if(!active)throw Error('Evaluate before exporting');const [p5,runtime]=await loadLibraries();const safe=s=>s.replace(/<\/script/gi,'<\\/script');const data=JSON.stringify({mode:active.dataset.mode,source:lastGood,appearance:settings,render:JSON.parse(active.dataset.render)}).replace(/</g,'\\u003c');download(new Blob([`<!doctype html><meta charset="utf-8"><title>Genereti Livecode</title><style>body{margin:0;background:#111}canvas{max-width:100%;}#staging{display:none}</style><div id="staging"></div><script>window.__GENERETI_STANDALONE__=${data}</script><script>${safe(p5)}</script><script>${safe(runtime)}</script>`],{type:'text/html'}),'genereti-livecode.html');}catch(error){status.textContent=error.message;}};
 json.onclick=()=>{const object={format:'genereti-livecode',version:1,language:value(node,'language')||'p5',code:draft,auto_update:!!value(node,'auto_update'),properties:node.properties};download(new Blob([JSON.stringify(object,null,2)+'\n'],{type:'application/json'}),'genereti-livecode.json');};
 script.onclick=()=>{const mode=value(node,'language')||'p5',extension={p5:'js',three:'js',strudel:'js',glsl:'frag',html:'html',markdown:'md'}[mode]||'txt';download(new Blob([draft],{type:'text/plain;charset=utf-8'}),`genereti-${mode}.${extension}`);};

 function applyView(){
  const overlay=show.value==='overlay';code.style.display=show.value==='output'?'none':'';stage.style.display=show.value==='code'?'none':'';
  if(overlay){stage.append(code);code.style.cssText='position:absolute;inset:0;z-index:2;height:100%';}else{container.insertBefore(code,divider);code.style.cssText='height:0;min-height:0;overflow:hidden;flex:1 1 0';}
  code.style.display=show.value==='output'?'none':'';divider.style.display=show.value==='both'?'':'none';code.style.flex=show.value==='both'?`${split} 1 0`:'1 1 0';stage.style.flex=show.value==='both'?`${1-split} 1 0`:'1 1 0';view?.setAppearance({...settings,overlay:overlay,fillHeight:true});layoutFrame();
 }
 let split=node.properties.generetiLivecodeSplit??.4;
 const divider=document.createElement('div');divider.setAttribute('role','separator');divider.setAttribute('aria-label','Code / output split');divider.setAttribute('aria-orientation','horizontal');divider.tabIndex=0;divider.title='Drag to resize code / output · arrows to adjust · double click to reset';divider.style.cssText='height:6px;min-height:6px;flex-shrink:0;border-top:1px solid var(--border-color,#555);cursor:row-resize;touch-action:none';container.insertBefore(divider,status);
 function saveSplit(next){split=Math.max(.1,Math.min(.9,next));node.properties.generetiLivecodeSplit=split;divider.setAttribute('aria-valuenow',String(Math.round(split*100)));applyView();}
 let splitDrag;divider.onpointerdown=event=>{event.preventDefault();event.stopPropagation();splitDrag={y:event.clientY,split,height:code.getBoundingClientRect().height+stage.getBoundingClientRect().height};divider.setPointerCapture(event.pointerId);};divider.onpointermove=event=>{if(splitDrag)saveSplit(splitDrag.split+(event.clientY-splitDrag.y)/splitDrag.height);};divider.onpointerup=divider.onpointercancel=()=>splitDrag=null;divider.ondblclick=()=>saveSplit(.4);divider.onkeydown=event=>{if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();event.stopPropagation();saveSplit(split+(event.key==='ArrowUp'?-.05:.05));}};
 const render={width:512,height:512,mode:'fixed',aspect:'free',fit:'contain',...node.properties.generetiLivecodeRender};
 const dimPanel=document.createElement('div');dimPanel.style.cssText='display:none;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px';dimPanel.setAttribute('role','tabpanel');settingsPanel.append(dimPanel);
 for(const [name,panel] of [['Editor',controls],['Render',dimPanel]]){const tab=document.createElement('button');tab.type='button';tab.textContent=name;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(name==='Editor'));tab.style.cssText='height:28px;padding:3px 10px;border:0;border-radius:6px;color:inherit;background:transparent;cursor:pointer';tabs.append(tab);tab.onclick=()=>{for(const child of tabs.children)child.setAttribute('aria-selected',String(child===tab));controls.style.display=panel===controls?'grid':'none';dimPanel.style.display=panel===dimPanel?'grid':'none';for(const picker of controls.querySelectorAll('details'))picker.open=false;};}
 function renderField(title,input){const label=document.createElement('label');label.textContent=title;label.style.cssText='display:grid;gap:4px;min-width:0;font-size:11px';input.style.cssText='width:100%;min-width:0;box-sizing:border-box;height:28px';label.append(input);dimPanel.append(label);}
 function renderChoice(key,title,choices){const select=document.createElement('select');select.title=title;select.setAttribute('aria-label',title);for(const [label,value] of choices)select.append(new Option(label,value));select.value=render[key];renderField(title.replace('Render ','').replace('Preview ',''),select);select.onchange=()=>{render[key]=select.value;saveRender();};return select;}
 const sizeMode=renderChoice('mode','Render sizing',[['Fixed','fixed'],['Auto · preview viewport','auto'],['Display size','screen']]);
 const aspect=renderChoice('aspect','Render aspect',[['Free','free'],['1:1','1'],['16:9','1.7777777778'],['9:16','0.5625'],['4:3','1.3333333333'],['3:2','1.5']]);
 const previewFit=renderChoice('fit','Preview fit',[['Contain','contain'],['Cover','cover'],['Stretch','fill'],['Native pixels','native']]);
 const preset=document.createElement('select');preset.title='Render preset';preset.append(new Option('Presets…',''));for(const [w,h] of [[256,256],[512,512],[768,768],[1280,720],[1920,1080],[720,1280]])preset.append(new Option(`${w} × ${h}`,`${w},${h}`));renderField('Preset',preset);preset.onchange=()=>{if(!preset.value)return;const [w,h]=preset.value.split(',').map(Number);Object.assign(render,{width:w,height:h,mode:'fixed',aspect:'free'});sizeMode.value='fixed';aspect.value='free';[...dimPanel.querySelectorAll('input')].forEach((input,i)=>input.value=i?h:w);saveRender();preset.value='';};
 const fullscreen=document.createElement('button');iconButton(fullscreen,'Fullscreen preview','<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/>');fullscreen.title='Fullscreen preview · auto sizing follows viewport';tools.append(fullscreen);fullscreen.onclick=async()=>{try{if(document.fullscreenElement===stage)await document.exitFullscreen();else await stage.requestFullscreen();}catch(error){status.textContent=error.message;}};
 function resolvedRender(){let width=render.width,height=render.height;if(render.mode==='auto'){width=stage.clientWidth||512;height=stage.clientHeight||300;}if(render.mode==='screen'){width=screen.width;height=screen.height;}const ratio=Number(render.aspect);if(ratio>0){height=width/ratio;}return {width:Math.max(64,Math.min(4096,Math.round(width))),height:Math.max(64,Math.min(4096,Math.round(height)))};}
 function saveRender(){node.properties.generetiLivecodeRender={...render};layoutFrame();if(active && render.fit===previewFit.value && render.mode==='fixed' && active.dataset.render===JSON.stringify(resolvedRender()))return;evaluate();}
 for(const key of ['width','height']){const input=document.createElement('input');input.type='number';input.min=64;input.max=4096;input.step=1;input.setAttribute('aria-label','Render '+key);input.value=render[key];renderField(key==='width'?'Width':'Height',input);input.onchange=()=>{render[key]=Math.max(64,Math.min(4096,Number(input.value)||512));input.value=render[key];saveRender();};}
 let frameWidth=render.width,frameHeight=render.height;
 function layoutFrame(){
  if(!active && !candidate)return;
  const width=stage.clientWidth,height=stage.clientHeight;
  for(const frame of [active,candidate])if(frame){const w=Number(frame.dataset.width)||render.width,h=Number(frame.dataset.height)||render.height;const fit=render.fit;const sx=fit==='native'?1:fit==='fill'?width/w:(fit==='cover'?Math.max:Math.min)(width/w,height/h);const sy=fit==='fill'?height/h:sx;frame.style.width=w+'px';frame.style.height=h+'px';frame.style.left=(width-w*sx)/2+'px';frame.style.top=(height-h*sy)/2+'px';frame.style.transform=`scale(${sx},${sy})`;frame.style.transformOrigin='top left';}
 }
 let resizeTimer;const resizeObserver=new ResizeObserver(()=>{layoutFrame();if(active && render.mode==='auto' && active.dataset.render!==JSON.stringify(resolvedRender())){clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(!disposed)evaluate();},300);}});resizeObserver.observe(stage);

 function saveAppearance(){node.properties.generetiLivecodeAppearance={...settings};view?.setAppearance({...settings,overlay:show.value==='overlay',fillHeight:true});post(active,{type:'appearance',appearance:settings});post(candidate,{type:'appearance',appearance:settings});}
 const drafts=new Map();let draftMode='p5';
 let draft=examples.p5,view,active=null,candidate=null,users=0,disposed=false,timer,epoch=0,candidateTimeout,pendingCapture=new Map(),captureId=0,lastGood='';
 function setDraft(source){draft=source;if(view&&view.state.doc.toString()!==source)view.dispatch({changes:{from:0,to:view.state.doc.length,insert:source}});}
 function createView(){view?.destroy();view=createEditor(code,draft,value(node,'language')||'p5',source=>{draft=source;clearTimeout(timer);if(value(node,'auto_update')&&!active?.dataset.stopped)timer=setTimeout(evaluate,400);},evaluate,{...settings,overlay:show.value==='overlay',fillHeight:true});view.formatDocument=()=>formatDocument();}
 createView();applyView();
 const widget=node.addDOMWidget(name,'GENERETI_LIVECODE',container,{serialize:true,getValue:()=>draft,setValue:source=>setDraft(source||examples[value(node,'language')||'p5'])});widget.computeSize=width=>[width,300];
 function syncHeight(){const host=container.closest('.lg-node');let height=node.size[1]-160;if(host){const scale=host.getBoundingClientRect().height/host.clientHeight||1;const top=(container.getBoundingClientRect().top-host.getBoundingClientRect().top)/scale;const total=parseFloat(getComputedStyle(host).getPropertyValue('--node-height'))||node.size[1];height=total-top-40;}container.style.height=Math.max(220,height)+'px';layoutFrame();}
 const parentResize=new ResizeObserver(syncHeight);function observeParent(){if(disposed)return;const parent=container.closest('.lg-node')||container.parentElement;if(!parent){requestAnimationFrame(observeParent);return;}syncHeight();parentResize.observe(parent);}requestAnimationFrame(observeParent);const previousResize=node.onResize;node.onResize=function(){const result=previousResize?.apply(this,arguments);requestAnimationFrame(syncHeight);return result;};
 const post=(frame,data)=>frame?.contentWindow?.postMessage(data,'*');
 function retire(frame){if(!frame)return;post(frame,{type:'dispose'});frame.style.opacity='0';frame.style.pointerEvents='none';setTimeout(()=>frame.remove(),50);}
 function removeCandidate(){clearTimeout(candidateTimeout);retire(candidate);candidate=null;}
 async function evaluate(sourceOverride,modeOverride){
  const sizing=resolvedRender();const generation=++epoch;const mode=modeOverride||value(node,'language')||'p5',source=typeof sourceOverride==='string'?sourceOverride:draft;
  status.textContent='Compiling…';
  try{
   const [p5,runtime]=await loadLibraries();if(disposed||generation!==epoch)return;
   if(active?.dataset.mode==='strudel'&&!active.dataset.stopped&&mode==='strudel'&&active.dataset.render===JSON.stringify(sizing)){post(active,{type:'compile',mode,source,revision:generation});return;}
   removeCandidate();const frame=document.createElement('iframe');frame.dataset.mode=mode;frame.dataset.source=source;frame.dataset.revision=generation;frame.title=`${mode} livecode preview`;frame.sandbox='allow-scripts';frame.allow='autoplay';frame.dataset.width=sizing.width;frame.dataset.height=sizing.height;frame.dataset.render=JSON.stringify(sizing);frame.style.cssText=`width:${sizing.width}px;height:${sizing.height}px;border:0;position:absolute;opacity:0;pointer-events:none;transform-origin:top left`;candidate=frame;stage.append(frame);layoutFrame();
   const safe=s=>s.replace(/<\/script/gi,'<\\/script');frame.srcdoc=`<!doctype html><style>html,body{margin:0;background:#111;width:100%;height:100%;overflow:hidden}body{display:flex;align-items:center;justify-content:center}canvas{max-width:100%;max-height:100%;object-fit:contain;touch-action:none}#staging{position:absolute;opacity:0;pointer-events:none}button{position:fixed;bottom:8px;right:8px}</style><div id="staging"></div><script>${safe(p5)}</script><script>${safe(runtime)}</script>`;
   candidateTimeout=setTimeout(()=>{if(candidate===frame){removeCandidate();status.textContent='Compile timed out · last working sketch retained';}},10000);
  }catch(error){status.textContent=`${error.message} · last working sketch retained`;}
 }
 run.onclick=()=>evaluate();
 stop.onclick=()=>{run.setAttribute('aria-pressed','false');stop.setAttribute('aria-pressed','true');clearTimeout(timer);++epoch;removeCandidate();post(active,{type:'stop'});if(active)active.dataset.stopped='true';run.setAttribute('aria-pressed','false');stop.setAttribute('aria-pressed','true');status.textContent='Stopped · last frame retained';};
 node._generetiEditorContext=()=>({source:draft,language:value(node,'language'),selection:view.state.selection.ranges.map(r=>({from:r.from,to:r.to,text:view.state.sliceDoc(r.from,r.to)})),status:status.textContent});
 node._generetiRun=()=>evaluate();node._generetiStop=()=>stop.onclick();
 container.addEventListener('keydown',event=>{if(event.isComposing)return;if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();event.stopImmediatePropagation();evaluate();}else if((event.ctrlKey||event.metaKey)&&(event.key==='.'||event.code==='Period')){event.preventDefault();event.stopImmediatePropagation();stop.onclick();}},true);
 function onMessage(event){
  const isCandidate=event.source===candidate?.contentWindow,isActive=event.source===active?.contentWindow;if(!isCandidate&&!isActive)return;
  const data=event.data;
  if(data.type==='request-run'&&isActive)evaluate();
  if(data.type==='stopped'&&isActive){clearTimeout(timer);active.dataset.stopped='true';run.setAttribute('aria-pressed','false');stop.setAttribute('aria-pressed','true');status.textContent='Stopped · last frame retained';}
  if(data.type==='boot'&&isCandidate){post(candidate,{type:'appearance',appearance:settings});post(candidate,{type:'compile',mode:candidate.dataset.mode,source:candidate.dataset.source,revision:Number(candidate.dataset.revision),render:JSON.parse(candidate.dataset.render)});}
  if(data.type==='ready'){
   if(isCandidate){clearTimeout(candidateTimeout);const old=active;active=candidate;candidate=null;active.style.opacity='1';active.style.pointerEvents='auto';retire(old);}
   if(data.width&&data.height){frameWidth=data.width;frameHeight=data.height;active.dataset.width=data.width;active.dataset.height=data.height;stage.style.aspectRatio=`${data.width}/${data.height}`;layoutFrame();}
   lastGood=data.source||active.dataset.source;active.dataset.source=lastGood;node.properties.generetiLivecodeLastGood={mode:active.dataset.mode,source:lastGood};status.textContent='Running';run.setAttribute('aria-pressed','true');stop.setAttribute('aria-pressed','false');if(users)post(active,{type:'live-start'});
  }
  if(data.type==='error'){status.textContent=`${data.message}\nLast working sketch retained`;if(isCandidate)removeCandidate();}
  if(data.type==='size'&&isActive){frameWidth=data.width;frameHeight=data.height;active.dataset.width=data.width;active.dataset.height=data.height;stage.style.aspectRatio=`${data.width}/${data.height}`;layoutFrame();}
  if(data.type==='live-frame'){
   try{if(isActive&&users)publishLive(node,data.bitmap);}finally{data.bitmap?.close();post(active,{type:'live-ack'});}
  }
  if(data.type==='draft'&&isActive)setDraft(data.source);
  if(data.type==='audio-state')status.textContent=`Running · audio ${data.state}`;
  if(data.type==='capture'||data.type==='capture-error'){const request=pendingCapture.get(data.id);if(request){clearTimeout(request.timeout);pendingCapture.delete(data.id);data.type==='capture'?request.resolve(data.data):request.reject(Error(data.message));}}
 }
 function onEditorShortcut(event){
  if(!event.isComposing&&event.key==='Escape'&&tools.querySelector('details[open]')){
   event.preventDefault();event.stopImmediatePropagation();dismissMenus();view.focus();return;
  }
  if(event.isComposing||!(event.ctrlKey||event.metaKey)||!view.dom.contains(document.activeElement))return;
  const key=event.key.toLowerCase();let action;
  if(event.shiftKey&&['Equal','Minus','NumpadAdd','NumpadSubtract'].includes(event.code))action=()=>{const increment=['Equal','NumpadAdd'].includes(event.code)?1:-1;settings.fontSize=Math.max(9,Math.min(36,Number(settings.fontSize||14)+increment));inputs.get('fontSize').value=settings.fontSize;saveAppearance();};else if(key==='z')action=()=>event.shiftKey?view.redo():view.undo();else if(key==='y')action=()=>view.redo();else if(key==='f'&&event.shiftKey)action=()=>formatDocument();else if(event.code==='Space')action=()=>view.complete();
  if(action){event.preventDefault();event.stopImmediatePropagation();action();}
 }
 function onEditorWheel(event){
  if(!event.shiftKey||!view.dom.contains(event.target))return;
  event.preventDefault();event.stopImmediatePropagation();
  const delta=Math.abs(event.deltaY)>=Math.abs(event.deltaX)?event.deltaY:event.deltaX;
  const multiplier=event.deltaMode===1?Number(settings.fontSize)*Number(settings.lineHeight):event.deltaMode===2?view.scrollDOM.clientHeight:1;
  view.scrollDOM.scrollTop+=delta*multiplier;
 }
 function dismissMenus(){for(const menu of tools.querySelectorAll('details[open]'))menu.open=false;}
 function onOutsidePointer(event){for(const menu of tools.querySelectorAll(':scope > details[open]'))if(!menu.contains(event.target))menu.open=false;}
 // Comfy binds graph undo before CodeMirror receives the event. Capture at
 // window level so editing code never undoes/removes the graph's nodes.
 window.addEventListener('keydown',onEditorShortcut,true);
 window.addEventListener('wheel',onEditorWheel,{capture:true,passive:false});
 window.addEventListener('pointerdown',onOutsidePointer,true);
 window.addEventListener('message',onMessage);
 function captureDataUrl(){if(!active)throw Error('Evaluate livecode before capturing');return new Promise((resolve,reject)=>{const id=++captureId;const timeout=setTimeout(()=>{pendingCapture.delete(id);reject(Error('Livecode capture timed out'));},5000);pendingCapture.set(id,{resolve,reject,timeout});post(active,{type:'capture',id});});}
 node._generetiLivecode={evaluate,captureDataUrl,get editor(){return view},get lastGood(){return lastGood},get active(){return active},settings,exportPng:()=>png.onclick(),exportHtml:()=>html.onclick()};
 node._generetiLiveSource={retain(){if(++users===1)post(active,{type:'live-start'});},release(){users=Math.max(0,users-1);if(!users)post(active,{type:'live-stop'});}};
 const previous=node.onRemoved;node.onRemoved=function(){disposed=true;++epoch;clearTimeout(timer);clearTimeout(resizeTimer);resizeObserver.disconnect();parentResize.disconnect();removeCandidate();retire(active);view.destroy();window.removeEventListener('message',onMessage);window.removeEventListener('keydown',onEditorShortcut,true);window.removeEventListener('wheel',onEditorWheel,true);window.removeEventListener('pointerdown',onOutsidePointer,true);for(const request of pendingCapture.values()){clearTimeout(request.timeout);request.reject(Error('Node removed'));}return previous?.apply(this,arguments);};
 node._livecodeConfigure=()=>{syncAutoUpdate();Object.assign(settings,node.properties.generetiLivecodeAppearance||{});Object.assign(customThemes,node.properties.generetiLivecodeThemes||{});refreshThemes();Object.assign(render,node.properties.generetiLivecodeRender||{});sizeMode.value=render.mode;aspect.value=render.aspect;previewFit.value=render.fit;for(const [i,input] of [...dimPanel.querySelectorAll('input')].entries())input.value=render[i?'height':'width'];for(const [key,input] of inputs){input.value=settings[key]??appearanceValues(settings)[key];if(input.type==='checkbox')input.checked=settings[key]!==false;}split=node.properties.generetiLivecodeSplit??.4;css.value=settings.css||'';wrap.checked=settings.wrap;show.value=node.properties.generetiLivecodeView||'both';applyView();draftMode=value(node,'language')||'p5';createView();const mode=node.widgets.find(w=>w.name==='language');if(mode&&!mode._livecode){const callback=mode.callback;mode.callback=function(next){callback?.apply(this,arguments);drafts.set(draftMode,draft);draftMode=next;setDraft(drafts.get(next)||examples[next]);createView();const auto=node.widgets.find(w=>w.name==='auto_update');if(auto)auto.value=next!=='strudel';syncAutoUpdate();};mode._livecode=true;}};
 return {widget};
}
async function serializeCanvas(node){
 const data=await node._generetiLivecode.captureDataUrl(),response=await fetch(data),file=new File([await response.blob()],`genereti-livecode-${Date.now()}.png`,{type:'image/png'}),body=new FormData();body.append('image',file);body.append('subfolder','genereti-livecode');body.append('type','temp');
 const upload=await api.fetchApi('/upload/image',{method:'POST',body});if(!upload.ok)throw Error(`Livecode upload failed (${upload.status})`);const result=await upload.json();return `${result.subfolder}/${result.name} [${result.type||'temp'}]`;
}
app.registerExtension({name:'Genereti.Livecode',beforeRegisterNodeDef(nodeType,nodeData){if(nodeData.name!=='GeneretiLivecode')return;nodeData.display_name=nodeType.title='ꘇ livecode';nodeData.search_aliases=[...new Set([...(nodeData.search_aliases||[]),'Genereti Livecode','livecode','live code','p5','GLSL','Three.js','Strudel'])];},getCustomWidgets(){return {
 GENERETI_LIVECODE:editorWidget,
 GENERETI_LIVECODE_CAPTURE(node,name){const widget=node.addWidget('text',name,'',()=>{});widget.type='hidden';widget.options={...widget.options,hidden:true};widget.computeSize=()=>[0,-4];widget.serializeValue=()=>serializeCanvas(node);return {widget};}
};},nodeCreated(node){if(node.comfyClass!=='GeneretiLivecode')return;if(['Genereti Livecode','GeneretiLivecode'].includes(node.title))node.title='ꘇ livecode';const prior=node.onConfigure;node.onConfigure=function(){prior?.apply(this,arguments);if(['Genereti Livecode','GeneretiLivecode'].includes(node.title))node.title='ꘇ livecode';node._livecodeConfigure?.();const saved=node.properties?.generetiLivecodeLastGood;if(saved&&typeof saved.source==='string')node._generetiLivecode.evaluate(saved.source,saved.mode);};queueMicrotask(()=>node._livecodeConfigure?.());}});
