import {GeneretiClient} from './genereti-client.js';
const $=id=>document.getElementById(id),SIZE=512;
let client=new GeneretiClient($('server').value),running=false,connected=false,appliedPrompt=$('prompt').value,bitmap=null,latestFrame=0,inFlight=false,inputRevision=0,encodedRevision=-1,encodedInput='',retryAt=0,lastGenerated=0,outputP,inputP,outputInk,inputImage=null;
const marks={input:[],output:[]};let currentStroke=null;
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function applyPrompt(){appliedPrompt=$('prompt').value;retryAt=0;}
function settings(){return {mode:'sketch',style:'base',prompt:appliedPrompt,seed:Number($('seed').value)||0,control_scale:Number($('control').value),preprocess:true,ai_upscaler:'off',noise_phase:0};}
function setRunning(value){running=value;$('live').textContent=value?'Pause':'Start live';}
function recordStroke(p,kind,erase){const color=erase?(kind==='input'?'#ffffff':'erase'):$('ink').value;const stroke={kind,color,width:Number($('brush').value)||6,points:[[p.mouseX,p.mouseY]]};marks[kind].push(stroke);currentStroke=stroke;}
function line(layer,a,b,stroke){layer.push();if(stroke.color==='erase')layer.erase();else layer.stroke(stroke.color);layer.strokeWeight(stroke.width);layer.line(...a,...b);layer.pop();if(stroke.color==='erase')layer.noErase();}
function installDrawing(p,kind,layer){p.mousePressed=()=>{if(p.mouseX<0||p.mouseY<0||p.mouseX>=SIZE||p.mouseY>=SIZE)return;recordStroke(p,kind,p.mouseButton===p.RIGHT);const a=currentStroke.points[0];line(layer(),a,[a[0]+.01,a[1]+.01],currentStroke);if(kind==='input')inputRevision++;return false;};p.mouseDragged=()=>{if(!currentStroke||currentStroke.kind!==kind)return;const point=[Math.max(0,Math.min(SIZE,p.mouseX)),Math.max(0,Math.min(SIZE,p.mouseY))];line(layer(),currentStroke.points.at(-1),point,currentStroke);currentStroke.points.push(point);if(kind==='input')inputRevision++;return false;};p.mouseReleased=()=>{currentStroke=null;};}
new p5(p=>{inputP=p;p.setup=()=>{p.createCanvas(SIZE,SIZE).parent('inputCanvas');p.pixelDensity(1);p.background(255);p.strokeCap(p.ROUND);p.noLoop();installDrawing(p,'input',()=>p);};});
new p5(p=>{outputP=p;p.setup=()=>{p.createCanvas(SIZE,SIZE).parent('outputCanvas');p.pixelDensity(1);outputInk=p.createGraphics(SIZE,SIZE);outputInk.pixelDensity(1);outputInk.strokeCap(p.ROUND);p.frameRate(30);installDrawing(p,'output',()=>outputInk);};p.draw=()=>{p.background(255);if(bitmap)p.drawingContext.drawImage(bitmap,0,0,SIZE,SIZE);const effect=$('effect').value;if(effect==='gray')p.filter(p.GRAY);if(effect==='threshold')p.filter(p.THRESHOLD,.5);if(effect==='posterize')p.filter(p.POSTERIZE,4);p.image(outputInk,0,0);};});
for(const element of document.querySelectorAll('.canvas-host'))element.addEventListener('contextmenu',e=>e.preventDefault());
function accept(frame){bitmap?.close();bitmap=frame.bitmap;latestFrame=frame.frame;}
async function connect(){if(inFlight){status('Wait for the current frame before reconnecting.');return;}setRunning(false);connected=false;$('connect').disabled=true;$('live').disabled=$('once').disabled=true;status('Loading 512 × 512 SDXS…');try{const base=new URL($('server').value);if(!['localhost','127.0.0.1','[::1]'].includes(base.hostname)||!['http:','https:'].includes(base.protocol))throw new Error('Use a localhost Genereti server.');client=new GeneretiClient(base.origin);const state=await client.status();if(!state.available_sizes.includes(SIZE))throw new Error('512px models are not installed. Run scripts/download_models.sh.');if(state.size!==SIZE)await client.configureSize(SIZE);const ready=await client.status();if(!ready.ready||!ready.controlnet)throw new Error(ready.error||'SDXS sketch model is not ready.');connected=true;$('live').disabled=$('once').disabled=false;status('SDXS sketch · 512 × 512 ready');}catch(e){status(e.message,true);}finally{$('connect').disabled=false;}}
async function sendFrame(){if(!connected||inFlight)return null;inFlight=true;const started=performance.now();try{const state=await client.status();if(state.size!==SIZE||!state.ready)throw new Error('Model configuration changed. Reconnect to 512px.');if(inputRevision!==encodedRevision){encodedInput=inputP.canvas.toDataURL('image/png');encodedRevision=inputRevision;}const result=await client.generate({image:encodedInput,...settings()});if(result){accept(result);const now=performance.now(),fps=lastGenerated?1000/(now-lastGenerated):0;lastGenerated=now;$('metrics').textContent=`${fps.toFixed(1)} fps · ${Math.round(now-started)} ms · model ${Math.round(result.inferenceMs)} ms`;status(`SDXS sketch · frame ${result.frame}`);}return result;}catch(e){retryAt=performance.now()+(e.status===429?1000:2000);if(e.status!==429)setRunning(false);status(e.status===429?'Generator busy: pause the other producer.':e.message,true);return null;}finally{inFlight=false;}}
async function receive(){if(inFlight)return;try{accept(await client.receive());status(`Received shared output · frame ${latestFrame}`);}catch(e){status(e.message,true);}}
function loop(){if(running&&!inFlight&&performance.now()>=retryAt)sendFrame();requestAnimationFrame(loop);}requestAnimationFrame(loop);
function clearInput(){inputP.background(255);inputImage=null;marks.input=[];inputRevision++;}
function clearOutput(){outputInk.clear();marks.output=[];}
function snapshot(){const raw=document.createElement('canvas');raw.width=raw.height=SIZE;if(bitmap)raw.getContext('2d').drawImage(bitmap,0,0,SIZE,SIZE);return {format:'genereti-p5-scene-v1',size:SIZE,settings:settings(),effect:$('effect').value,input:inputP.canvas.toDataURL('image/png'),output:outputP.canvas.toDataURL('image/png'),rawOutput:bitmap?raw.toDataURL('image/png'):null,outputMarks:outputInk.canvas.toDataURL('image/png'),marks:structuredClone(marks),frame:latestFrame};}
async function decode(url){const image=new Image();image.src=url;await image.decode();return image;}
async function load(scene){if(scene.format!=='genereti-p5-scene-v1'||scene.size!==SIZE)throw new Error('Choose a Genereti p5 scene at 512px.');setRunning(false);const image=await decode(scene.input),ink=scene.outputMarks?await decode(scene.outputMarks):null,output=scene.rawOutput?await decode(scene.rawOutput):null;clearInput();inputP.drawingContext.drawImage(image,0,0,SIZE,SIZE);inputRevision++;clearOutput();if(ink)outputInk.drawingContext.drawImage(ink,0,0,SIZE,SIZE);if(output){bitmap?.close();bitmap=await createImageBitmap(output);}appliedPrompt=scene.settings.prompt;$('prompt').value=appliedPrompt;$('seed').value=scene.settings.seed;$('control').value=scene.settings.control_scale;$('effect').value=scene.effect||'plain';marks.input=scene.marks?.input||[];marks.output=scene.marks?.output||[];latestFrame=scene.frame||0;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('connect').onclick=connect;$('live').onclick=()=>setRunning(!running);$('once').onclick=sendFrame;$('receive').onclick=receive;$('apply').onclick=applyPrompt;$('prompt').oninput=()=>{if($('livePrompt').checked)applyPrompt();};$('livePrompt').onchange=()=>{if($('livePrompt').checked)applyPrompt();};$('prompt').onkeydown=e=>{if(!e.isComposing&&(e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();applyPrompt();}};
$('clearInput').onclick=clearInput;$('clearOutput').onclick=clearOutput;
$('example').onclick=()=>{clearInput();inputP.noFill();inputP.stroke('#111');inputP.strokeWeight(5);inputP.bezier(70,425,200,110,280,390,440,80);inputP.circle(365,140,85);inputP.triangle(120,270,245,235,210,400);inputRevision++;};
$('outputToInput').onclick=()=>{inputP.drawingContext.drawImage(outputP.canvas,0,0);marks.input=[];inputRevision++;};
$('saveState').onclick=()=>download(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),'genereti-p5-scene.json');$('loadState').onclick=()=>$('stateFile').click();$('stateFile').onchange=async()=>{try{const file=$('stateFile').files[0];if(!file)return;if(file.size>16_000_000)throw new Error('Scene is too large.');await load(JSON.parse(await file.text()));status('Canvas state loaded');}catch(e){status(e.message,true);}finally{$('stateFile').value='';}};
$('saveImage').onclick=()=>outputP.canvas.toBlob(blob=>download(blob,'genereti-p5-output.png'));
window.generetiP5={connect,sendFrame,receive,snapshot,load,clearInput,clearOutput,setPrompt(value){$('prompt').value=value;applyPrompt();},setRunning,setEffect(value){if(!['plain','gray','threshold','posterize'].includes(value))throw new Error('Unknown effect');$('effect').value=value;},get state(){return {connected,running,busy:inFlight,frame:latestFrame,inputRevision,settings:settings()};}};
window.addEventListener('beforeunload',()=>{setRunning(false);bitmap?.close();});
